### PR TITLE
Increase UPDATE/DELETE concurrency

### LINKED ISSUE #370: Improve locking semantics for UPDATE / UPSERT / DELETE
When the master node receives an `UPDATE`, and has default config settings, it acquires an exclusive lock on the shard id. This leads to a notable performance degradation for `UPDATE`, `INSERT ... ON CONFLICT UPDATE`, and `DELETE` statements.

If the user enables `all_modifications_commutative`, we instead acquire a shared lock.

This issue relates to investigating and implementing a locking policy that improves performance for `UPDATE` statements.

### PR DESCRIPTION
**Pull request by jasonmp85**
Based on a proposal by @anarazel. Rather than dealing with concurrency on the master and sending solely the `UPDATE` or `DELETE` command to remotes, `UPDATE` and `DELETE` (also "`UPSERT`") will now make two round trips:

  1. Send a string consisting of `BEGIN;` followed by the actual `UPDATE`, etc. text
  2. Send `COMMIT`

The first step is performed across all placements, then the second. This permits us to rely on row locks on the remotes rather than locking on the master.

Competing `UPDATE` or `DELETE` commands will either block on one another or fail in such a way that they'll mark inconsistent shards as inactive; however, we have to worry about racing `INSERT`s, as they no longer block `UPDATE` or `DELETE` commands. As they are purely additive, it is sufficient to ensure that all executions of a task modify the same number of rows. Executions exhibiting a discrepancy result in the offending placements being marked inactive.

Finally, `COPY` is now an issue. It acquires a `Share` lock on a shard, hoping to prevent e.g. `UPDATE` and `DELETE` commands. Since they should no longer need a lock, I need to figure out why `COPY` does this in the first place. It uses 2PC, so it _should_ be sufficient to stop _all_ writes for a short time, send `BEGIN` to all nodes, then unlock (rather than locking for the whole `COPY`). I'm going to run this by @marcocitus, but in the interim, I've changed `UPDATE` and `DELETE` to use `RowExclusive`, which will continue to conflict with `COPY` (as before) but will not conflict with itself (or `INSERT`, which now uses `NoLock` but never conflicted with `COPY` to begin with).

Fixes #370

### CODE REVIEW

**Comment by marcocitus** [comment]
> As they are purely additive, it is sufficient to ensure that all executions of a task modify the same number of rows. Executions exhibiting a discrepancy result in the offending placements being marked inactive.

Hmz, inserts don't block updates. A concurrent update just works on the existing snapshot. So does that mean an insert could outrace an update and we'd mark a placement as inactive? (which seems quite likely)

    session 1 worker 1: begin; update; <-- before session 2 commits, does not update new row
    session 2 worker 1: begin; insert;
    session 2 worker 2: begin; insert;
    session 2 worker 1: commit;
    session 2 worker 2: commit;
    session 1 worker 2: begin; update;  <-- after session 2 commits, updates new row
    session 1 worker 1: commit;
    session 1 worker 2: commit;

>  It uses 2PC, so it should be sufficient to stop all writes for a short time, send BEGIN to all nodes, then unlock (rather than locking for the whole COPY). 

COPY also doesn't block updates, so the result of the update depends on whether it comes before or after the COPY commits.

**Comment by marcocitus** [comment]
> COPY also doesn't block updates

I meant in PostgreSQL. COPY on a distributed table currently does block updates on the distributed table.

**Comment by jasonmp85** [comment]
@marcocitus, I added a summary of our discussion into #370. I'll update this PR with stricter `INSERT` vs `UPDATE` locking unless I think of a better solution (or one comes to me via @anarazel).

**Comment by anarazel** [comment]
@jasonmp85 If you don't mind I'm taking off the needs-review tag and assignment? Afaics this needs to be updated based on our in-person discussion.

**Comment by jasonmp85** [comment]
@anarazel Yup.

Don't take off the needs review tag. It's automated.

**Comment by jasonmp85** [comment]
Closing this based on our discussions last week. I'll put a recap of the discussion into #370.

**Pull request closed without merging**
