### PR TITLE
Remove redundant implementations of error funcs.

### PR DESCRIPTION
**Pull request by amosbird**
This patch does some basic cleaning jobs. It removes duplicated
implementations of ReportRemoteError() and related ones and adjusts
regression tests.

### CODE REVIEW

**Comment by citus-github** [comment]
Hi @amosbird, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://cla.citusdata.com).

**Comment by lfittl** [comment]
@amosbird I noticed that you already clicked through a test version of our CLA (a team member might have sent it before it was ready). I'll send you a new one shortly that is the one we need - sorry for the extra work.

**Comment by citus-github** [comment]
You did it @amosbird!

Thank you for signing the Citus Data Contributor License Agreement. We can now accept this contribution and all future contributions from you.

Somebody from our team will proceed with code review.

**Comment by jasonmp85** [comment]
I rebased your commit, fixed formatting (see the [`citus_indent`](https://github.com/citusdata/tools) tool to apply our style), and merged. Thanks for your contribution!

**Pull request closed without merging**
