### PR TITLE
Remove copyright years

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
This PR removes copyright year.

The following command from the root is used for updating:
`grep -rli '2012-2015' * | xargs -i@ sed -i 's/2012-2015/2012-2019/g' @`
`grep -rli '2012-2016' * | xargs -i@ sed -i 's/2012-2016/2012-2019/g' @`
`grep -rli '2012-2017' * | xargs -i@ sed -i 's/2012-2017/2012-2019/g' @`
`grep -rli '2012-2018' * | xargs -i@ sed -i 's/2012-2018/2012-2019/g' @`
`grep -rli ' 2015, Ci' * | xargs -i@ sed -i 's/ 2015, Ci/ 2012-2019, Ci/g' @`
`grep -rli ' 2016, Ci' * | xargs -i@ sed -i 's/ 2016, Ci/ 2012-2019, Ci/g' @`
`grep -rli ' 2017, Ci' * | xargs -i@ sed -i 's/ 2017, Ci/ 2012-2019, Ci/g' @`
`grep -rli ' 2018, Ci' * | xargs -i@ sed -i 's/ 2018, Ci/ 2012-2019, Ci/g' @`
`grep -rli '2016-2016' * | xargs -i@ sed -i 's/2016-2016/2012-2019/g' @`
`grep -rli '2017-2017' * | xargs -i@ sed -i 's/2017-2017/2012-2019/g' @`

And finally:
`grep -rli '2012-2019, Citus Data, Inc.' * | xargs -i@ sed -i 's/2012-2019, Citus Data, Inc./Citus Data, Inc./g' @`

### CODE REVIEW

**Comment by hanefi** [comment]
We do not always state intervals in the copyright notices in files. While you are at it, shall we make them conform to the same pattern?

Some examples:

https://github.com/citusdata/citus/blob/169d2f193fb8e58f5425ac51668e93404501fc52/src/backend/distributed/commands/extension.c#L6

https://github.com/citusdata/citus/blob/169d2f193fb8e58f5425ac51668e93404501fc52/src/backend/distributed/executor/intermediate_results.c#L6

**Comment by SaitTalhaNisanci** [comment]
@hanefi That makes sense, I have updated the PR to include those too.

**Comment by metdos** [comment]
@lfittl do you have any idea about these changes? Shall we do it, or is it unnecessary?

**Comment by lfittl** [comment]
@metdos I don't think we need the year in there at all, but we might need to adjust some other details. I'll send you an internal email.

**Comment by lfittl** [comment]
@SaitTalhaNisanci @metdos Let's remove the year number, and just have the copyright notice as follows:

```
Copyright (c) Citus Data, Inc.
```

**Comment by marcocitus** [comment]
would be nice to merge this

**Pull request merged**
