### PR TITLE
Introduce list_empty macro

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**

### CODE REVIEW

**Review by onurctirtir — COMMENTED** [review]
Seems that we have still some places doing `== NIL` or `!= NIL` in code base

**Review by onurctirtir — APPROVED** [review]
Verified nearly %60 of the changes, LGTM.
I believe we should have a similar pr in enterprise too.

**Review by onderkalaci — COMMENTED** [review]
Although it is simple, it touches every code-path. So, can we wait to merge until we cut the release? We might introduce subtle bugs as we are already in the middle of testing?

**Comment by SaitTalhaNisanci** [comment]
As a reference the base regex: `([a-z|A-Z|\-|>|\*|_]+)` to match the list name

**Comment by metdos** [comment]
> Although it is simple, it touches every code-path. So, can we wait to merge until we cut the release? We might introduce subtle bugs as we are already in the middle of testing?

Exactly, let's wait a bit before merging this.

**Comment by metdos** [comment]
> Although it is simple, it touches every code-path. So, can we wait to merge until we cut the release? We might introduce subtle bugs as we are already in the middle of testing?

Exactly, let's wait a bit before merging this.

**Comment by SaitTalhaNisanci** [comment]
This PR is outdated now but if we find this useful, we can use a regex to replaces cases like:
- list_length(X) > 0 -----> !list_empty(X)
- list_length(X> == 0 -----> list_empty(X)
- X == nil ----> list_empty(X)
- X != nil ----> !list_empty(X)

**Pull request closed without merging**
