### PR TITLE
Expand recursive planning for distributed tables and recurring outer/semi joins

### PR DESCRIPTION
**Pull request by onderkalaci**
This PR is a prototype, and requires several improvements before merging. 

It enables good chunk of complex SQL queries that used be not supported. The improvements are mostly around subquery/cte joins with tables and outer joins with recurring tuples (e.g., reference table or intermediate results).

Though I started with a single improvement in my mind, I ended up implementing the second one as well to complement the first one which is by itself a useful feature.

- Expand recursive planning for tables
- Expand recursive planning for recursively planning inner parts of recurring tuple joins

The PR itself may not be performant for many cases where all the distributed table (or even some of the columns) needs to pulled to the coordinator** and pushed back. However, this can be considered a step towards future improvements. This PR, in combination with #2481 and an enhanced version of the implementation in #2305 could enable `Repartition via Coordinator`. Coupled with Citus MX, we might become closer to replace the existing repartitioning support. Though, we should find a way to execute `push` part of `pull & push` in parallel to compete with the current repartitioning implementation. Can we implement `Parallel COPY` in Postgres and use it?

 The coverage of this PR is tightly coupled with #2481, which enables (recurring tuple OUTER JOIN recurring tuple). And, this PR could yield lots of those joins.

 Basic algorithm to implement the changes:

 - Expand recursive planning for tables 

    - Simply convert "table" into `(SELECT required_columns FROM table)`
    - required_columns: The columns that the query refers
    - push all the filters that exists on the table in to the subquery, so actually: `(SELECT required_columns FROM table WHERE filters)`
    - Postgres pushes as much filters as possible, and we use those information to generate the wrapper subquery
    - Finally, call `RecursivelyPlanSubquery()` on the newly created subquery
    - Do this for failed non-colocated joins and failed recurrig tuple checks due to the table

 - Expand recursive planning for recursively planning inner parts of recurring tuple joins
    - During recursive planning, call `DeferredErrorIfUnsupportedRecurringTuplesJoin()`. If the function returns error, we know that there is no other way of executing this query.
    - Thus, get the inner part of the join that led to the error
    - If it is a relation, follow the above algorithm. If it is a subquery, we already know what to do via `RecursivelyPlanSubquery()`.

TODOs:
- [ ] Fix 9.6 regression tests
- [ ] Add more specific tests
- [ ] Probably merge it via two different PRs
- [ ] Improve the algorithm for calculating required_columns. For example, if a column appears only as a filter, we shouldn't pull it, but we do it now.
- [ ] Even though we don't need a column at all, we're currently adding it to the target list like `NULL::int as user_id`. Instead, we could only add the required columns and travers the remaining of query tree to update the references to those columns.
- [ ] We currently ignore FULL OUTER JOINS, which should be simple to add
- [ ] There are two regressions in the tests. Make sure that those are fixed with #2481
- [ ] Improve logging. We currently do not mention about recursive relation planning, which should be mentioned. Otherwirse, it'd be pretty confusing for the users.
- [ ] Restriction eq. codes rely on RTE to be `RTE_SUBQUERY`. However, we've now enough references to `RTE_RELATION`, so make those functions operate on `RTE_RELATION` as well
- [ ] Test with edge cases such as dropped columns, prepared statements, insert..select via coordinator etc.
- [ ] Consider LATERAL or any other correlated query cases some more

Any feedback is welcome!

** luckily we already have 1GB max limit of intermediate results

### CODE REVIEW

**Comment by marcocitus** [comment]
In terms of [TPC-H](https://github.com/citusdata/citus/issues/1862), this PR adds support for Q13 and Q22.

**Comment by marcocitus** [comment]
> So, as far as I remember, Q21 is definitely not solved by de-correlation, but Q20 is still a candidate because the correlations are eq. operators.

Q21 is already supported if only lineitem and orders are distributed.

**Comment by saimicrosoft** [comment]
@onderkalaci  +1. Customer ran into this in a technical session today. Overall SQL coverage has improved tremendously but still this error comes up often.

**Comment by onderkalaci** [comment]
Some of the codes/tests here are already merged to main branch via: https://github.com/citusdata/citus/pull/4358

The rest is mostly going to be overridden via (or a follow up): https://github.com/citusdata/citus/pull/6219

**Pull request closed without merging**
