### PR TITLE
Update to errmsg for mixed location insert into

### LINKED ISSUE #1432: confusing error message on mixed location insert select
current wording:

```
can't mix local and distributed relations in one query
```

Proposed:
```
cannot plan queries that include both local and distributed relations
```
pull request:

- https://github.com/citusdata/citus/pull/1431

related: 
 - https://github.com/citusdata/citus/pull/859

### PR DESCRIPTION
**Pull request by jmunsch**
i was very confused by the usage of "regular"

Fixes #1432

### CODE REVIEW

**Comment by jmunsch** [comment]
I haven't received the email for the CLA. I am willing to sign it. If i receive it.

james.a.munsch@gmail.com

**Comment by lithp** [comment]
@jmunsch apologies for the delay, trying to reach out to someone who can help you. Thanks for the PR, by the way! You're right, this error message is indeed a little less confusing.

**Comment by lithp** [comment]
Modulo one small change I'm happy to merge this once the CLA is figured out: The extra newline here is a bit gratuitous. We use [a 90 column](https://github.com/citusdata/tools/blob/develop/uncrustify/citus-style.cfg#L1346) code width so there's no need to split the error message across three different lines here.

**Comment by lithp** [comment]
Dropping a note that this will fix #1431

**Comment by lfittl** [comment]
@jmunsch Apologies, our CLA process currently requires manual review (thanks to DocuSign's API restrictions) and I was out at PGCon so only got to this now. Should be all good for this, and any future PRs. Thanks for the contribution!

**Comment by jmunsch** [comment]
no problem, pushed out the column width change. 
many thanks for the slick code.

**Comment by lithp** [comment]
@jmunsch Sorry to make you do this, I would do it myself but I don't think I can push to this branch on your repo. While we're touching this comment could it say `cannot plan queries *which* include both local and distributed relations` instead of `cannot plan queries *that* include both local and distributed relations`. After that I'll merge.

**Comment by jmunsch** [comment]
@lithp np

**Comment by lithp** [comment]
Ah, now the tests are failing because the error message has changed. It looks like there aren't many tests which hit this error message, there's a diff [here](https://travis-ci.org/citusdata/citus/jobs/236443850#L3584) with the test files (`expected/*.out`) which need to be changed for Travis to allow this PR.

**Comment by ozgune** [comment]
@jmunsch -- Thanks for submitting this change to Citus.

@lithp / @metdos / @jmunsch -- I just wanted to make sure that this pull request doesn't get lost. It looks like the change to wording broke our regression tests. This issue now seems to be fixed. Are we good to merge this change?

**Comment by metdos** [comment]
> @lithp / @metdos / @jmunsch -- I just wanted to make sure that this pull request doesn't get lost. It looks like the change to wording broke our regression tests. This issue now seems to be fixed. Are we good to merge this change?

@jmunsch,  If you can squash your commits to a single one and use first letter capitalized commit message, I think we can merge it. Thanks :)

**Comment by jmunsch** [comment]
@metdos i think i did the squash and rebase correctly. let me know.

Thanks ya'll for being accommodating.

**Comment by metdos** [comment]
Looks good, thanks, @jmunsch. I'm merging this.

**Pull request merged**
