### PR TITLE
Changes trigger type from 'pr' into 'branch'

### PR DESCRIPTION
**Pull request by gurkanindibay**
DESCRIPTION: Previously trigger type was pull_request and events were opened, reopened and synchronize.
In PR #6623, packaging pipeline was not triggered and PR was blocked . It may be a bug in GH Actions side.
To make sure of execution of the pipeline, I changed pipeline execution type into 'branches'

### CODE REVIEW

**Comment by JelteF** [comment]
Seems to be that's indeed the cause: https://github.com/orgs/community/discussions/26304

**Comment by gurkanindibay** [comment]
> I'm not sure this change is actually needed. I think the pull request event would have fired on the PR in question if the merge conflict would have been resolved.

It's a confusing issue I think. It's impossible for someone to find out that there is a merge conflict if GH Actions is not triggered
I think we may trigger on branch push

@hanefi @JelteF let us decide. Should we merge or not? My vote is on to merge

**Comment by hanefi** [comment]
> @hanefi @JelteF let us decide. Should we merge or not? My vote is on to merge

I vote on closing this PR without merging after checking the discussions in the link Jelte shared. The user will definitely solve merge conflicts and rebase. This will trigger all the tests anyway.

The downside of this decision is that we need to educate team members as this design may look counterintuitive to most of us.

**Comment by gurkanindibay** [comment]
We are closing without merging since merge conflict causes this problem. We will wait for the team to solve merge conflicts in such case

**Pull request closed without merging**
