### PR TITLE
Add logic to propagate SET LOCAL at xact start

### PR DESCRIPTION
**Pull request by jasonmp85**
Partially addresses #1327 (which discusses _all_ config, not just `SET LOCAL`)

DESCRIPTION: Add logic to propagate SET LOCAL at xact start

# Tasks
  - [ ] Add failing SQL test
  - [ ] Add GUC to whitelist propagated settings (for now); do not allow PostgreSQL ones (for now)
  - [ ] During transactions, detect matching `SET LOCAL` commands and…
  - [ ] Push down to any already-open remote transactions, and…
  - [ ] Append to a list of needed local settings for any further remote transactions, and…
  - [ ] During any subsequent remote transactions, add the `SET` commands after the initial `BEGIN` (but in the same network hop)
  - [ ] Consider enhancements (perhaps propagate for functions or even for single-statement remote commands, etc.)
  - [ ] Show test passes

### CODE REVIEW

**Comment by jasonmp85** [comment]
# MVP: Transaction Blocks

We'll want to keep track of any `SET LOCAL` things in the local transaction and push them down during any `BEGIN` to appropriate workers. Maybe "slow" (though I'm not actually sure of that, honestly), but correct/sufficient for a lot of stuff to become possible (including @mkurz's RLS policies).

# Additional Enhancements

OK, so in addition to explicit `SET LOCAL` commands within `BEGIN`, it appears there are two other places this could work…

## Functions

Declarations of functions can include configuration that is set/reset as the functions are entered/exited, respectively. Now that functions use transactions, propagating this should be straightforward.

## Multi-Statement Commands

This is a bit arcane, but it _is_ possible to use `SET LOCAL` without an explicit transaction block or function call. In particular, look at this…

```
psql 'SET LOCAL DateStyle TO SQL; SELECT now()' -c 'SHOW DateStyle;' postgres
┌───────────────────────────────┐
│              now              │
├───────────────────────────────┤
│ 04/24/2019 12:24:34.95311 MDT │
└───────────────────────────────┘
(1 row)

Time: 0.556 ms
┌───────────┐
│ DateStyle │
├───────────┤
│ ISO, MDY  │
└───────────┘
(1 row)

Time: 0.118 ms
```

The custom `DateStyle` appears to take affect for the `SELECT`. This means we could (in theory) preface SQL we generate (going to workers) with various `SET LOCAL` statements in order to force those single-SQL commands (not in transaction blocks) to run with the desired settings. As you can see above, the date style returns during the next transaction.

_BUT JASON ARE YOU SURE EACH `-c` COMMAND RUNS IN THE SAME CONNECTION?_

```
psql -c 'SELECT pg_backend_pid();' -c 'SELECT pg_backend_pid();' postgres
┌────────────────┐
│ pg_backend_pid │
├────────────────┤
│          16050 │
└────────────────┘
(1 row)

Time: 0.522 ms
┌────────────────┐
│ pg_backend_pid │
├────────────────┤
│          16050 │
└────────────────┘
(1 row)

Time: 0.103 ms
```

Yes, I am.

**Comment by mkurz** [comment]
@jasonmp85 Awesome you work on this! Any ETA?

**Comment by jasonmp85** [comment]
> Any ETA?

I mean, not committing to an ETA on a public issue, but: I'm working on it!

When I get some code up maybe you can try it if it's still pressing for you.

**Comment by mkurz** [comment]
? Why is this pull request marked as merged?

**Comment by onderkalaci** [comment]
> ? Why is this pull request marked as merged?

That's very interesting. I'm shown as the person who merged the PR. Well, I merged some other PRs to master and other branches. I wonder is that a bug on github's side? Luckily there are no commits in this PR, so that shouldn't be a problem. @jasonmp85 I'm leaving this as-is for now, you'd probably need to open another PR?

**Comment by mkurz** [comment]
Yeah, this looks like a bug in GitHub...

> And, it looks like another commit that I merged to master yesterday closed this PR.

So you merged that commit yesterday? However, this pull request here got "merged" 35 minutes ago (at the time of your writing)... I am pretty sure GitHub messed up this one...
Also, this pull request is/was a "draft pull request", which is quite a new feature in GitHub, so maybe something is wrong with that...

**Comment by jasonmp85** [comment]
Hm, yeah I pushed the `HEAD` of `master` to a new branch and "opened" a PR with no commits to merge. I assume pushing that `master` ref again closed this. I'll re-open.

**Comment by jasonmp85** [comment]
Ok, it's in #2689 now.

**Pull request merged**
