### PR TITLE
Make enterprise features open source

### PR DESCRIPTION
**Pull request by JelteF**
This PR makes all of the features open source that were previously only
available in Citus Enterprise.

Features that this adds:
1. Non blocking shard moves/shard rebalancer
   (`citus.logical_replication_timeout`)
2. Propagation of CREATE/DROP/ALTER ROLE statements
3. Propagation of GRANT statements
4. Propagation of CLUSTER statements
5. Propagation of ALTER DATABASE ... OWNER TO ...
6. Optimization for COPY when loading JSON to avoid double parsing of
   the JSON object (`citus.skip_jsonb_validation_in_copy`)
7. Support for row level security
8. Support for `pg_dist_authinfo`, which allows storing different
   authentication options for different users, e.g. you can store
   passwords or certificates here.
9. Support for `pg_dist_poolinfo`, which allows using connection poolers
   in between coordinator and workers
10. Tracking distributed query execution times using
   citus_stat_statements (`citus.stat_statements_max`,
   `citus.stat_statements_purge_interval`,
   `citus.stat_statements_track`). This is disabled by default.
11. Blocking tenant_isolation
12. Support for `sslkey` and `sslcert` in `citus.node_conninfo`

### CODE REVIEW

**Review by onderkalaci — APPROVED** [review]
Steps are documented on https://github.com/citusdata/citus-enterprise/pull/818 and review has  been done there.

**Comment by maziar-dandc** [comment]
Wow nice! Will the enterprise version repository be retired and all development moved over to the main repo?

**Comment by marcocitus** [comment]
> Wow nice! Will the enterprise version repository be retired and all development moved over to the main repo?

Pretty much. To be honest almost all development was already on this repo. We mainly merged this repo into the enterprise repo. We might still keep it around as a mirror for hot fixes.

**Comment by cnmade** [comment]
Great works. thanks for your greate works.

**Comment by viggy28** [comment]
Just leaving my tweet from three days ago https://twitter.com/viggy28/status/1536157371465990144

This is amazing.

**Comment by viggy28** [comment]
What about citus MX feature https://docs.citusdata.com/en/v9.3/arch/mx.html ?

**Comment by hlakshmi** [comment]
Thanks a lot this. Is there a plan to open source the Citus Warp tool which is used for migrating to Citus without downtime?

**Comment by marcocitus** [comment]
> What about citus MX feature https://docs.citusdata.com/en/v9.3/arch/mx.html ?

It's fully integrated into Citus 11. You can run distributed queries from any node. (DDL still needs to go via the coordinator)

**Pull request merged**
