### PR TITLE
Bump PG15 CI images to rc2

### PR DESCRIPTION
**Pull request by hanefi**
When bumping to RC2, we needed to update one test. The following is the commit message for the change:

Remove an alternative output as PG reverts commit

PG15 introduced an optimization on GROUP BY keys that is now reverted on
RC2.

Relevant PG Commit:
Revert "Optimize order of GROUP BY keys".
443df6e2db932a7cd6d85ddfb67e11a43345130d

Depends on: https://github.com/citusdata/the-process/pull/94

### CODE REVIEW

**Comment by naisila** [comment]
There is also the `enable_group_by_reordering` GUC that should be removed from a couple of tests. This GUC was introduced in https://github.com/postgres/postgres/commit/db0d67db2401eb6238ccc04c6407a4fd4f985832 
> This introduces a new GUC enable_group_by_reordering, so that the optimization may be disabled if needed.

I will remove those and update this PR if that's okay.

**Comment by naisila** [comment]
Thanks for letting me know. In that case I will review the PR when you commit those changes as well.

**Comment by naisila** [comment]
I am getting a failure in `make check-multi` in `citus_table_triggers` test. Maybe something to do with my local, but I can't investigate it right now, hence can't approve this PR today. Will look into it tomorrow: meanwhile it would be good if you can verify that `citus_table_triggers` passes on your local machine with pg15rc2.

The failure in `citus_table_triggers.out` is:
```diff
CREATE TRIGGER test_table_delete
     AFTER DELETE ON test_table
     FOR EACH STATEMENT
     EXECUTE FUNCTION test_table_trigger_function();
 SELECT master_get_table_ddl_events('test_table');
....
- ALTER TABLE table_triggers_schema.test_table ENABLE TRIGGER test_table_delete;
+ ALTER TABLE table_triggers_schema.test_table ENABLE TRIGGER \x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F;
```

**Review by naisila — COMMENTED** [review]
I am getting a failure in `make check-multi` in `citus_table_triggers` test. Maybe something to do with my local, but I can't investigate it right now, hence can't approve this PR today. Will look into it tomorrow: meanwhile it would be good if you can verify that `citus_table_triggers` passes on your local machine with pg15rc2.

The failure in `citus_table_triggers.out` is:
```diff
CREATE TRIGGER test_table_delete
     AFTER DELETE ON test_table
     FOR EACH STATEMENT
     EXECUTE FUNCTION test_table_trigger_function();
 SELECT master_get_table_ddl_events('test_table');
....
- ALTER TABLE table_triggers_schema.test_table ENABLE TRIGGER test_table_delete;
+ ALTER TABLE table_triggers_schema.test_table ENABLE TRIGGER \x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F\x7F;
```

**Comment by hanefi** [comment]
Onur fixed that test failure in another pr. The test should now pass after my last merge commit from main into this branch.

**Comment by hanefi** [comment]
For reference, here is the PR that fixed the failure mentioned earlier: #6413

**Review by naisila — APPROVED** [review]

**Pull request merged**
