### PR TITLE
Treat nodePort as the 64bit integer it is.

### LINKED ISSUE #408: error during compilation
Hello.
I try to make citus from source.
I set  PG_CONFIG.
When I do make, I have next error:
What is it? Whot do I not right?

In file included from /home/worker1/soft/pg_sql-worker-1/include/postgresql/server/postgres.h:47:0,
                 from master/master_create_shards.c:13:
master/master_create_shards.c: In function ‘master_create_worker_shards’:
/home/worker1/soft/citus/src/include/distributed/master_metadata_utility.h:25:37: error: invalid suffix "ULLL" on integer constant
 #define HASH_TOKEN_COUNT INT64CONST(4294967296UL)
                                     ^
/home/worker1/soft/pg_sql-worker-1/include/postgresql/server/c.h:280:33: note: in definition of macro ‘INT64CONST’
 #define INT64CONST(x)  ((int64) x##LL)
                                 ^
master/master_create_shards.c:118:23: note: in expansion of macro ‘HASH_TOKEN_COUNT’
  hashTokenIncrement = HASH_TOKEN_COUNT / shardCount;
                       ^
make[1]: *** [master/master_create_shards.o] Error 1

### LINKED ISSUE #422: Crash when running 32-bit Citus
The continuation to #408. Here's the stacktrace valgrind returns when running `master_create_empty_shard`.

````
==15624== Process terminating with default action of signal 11 (SIGSEGV): dumping core  
==15624==  Access not within mapped region at address 0x25E4                            
==15624==    at 0x402EE80: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==15624==    by 0x80A66F8: memcpy (string3.h:51)                                        
==15624==    by 0x80A66F8: heap_fill_tuple (heaptuple.c:277)                            
==15624==    by 0x80A757C: heap_form_tuple (heaptuple.c:768)                            
==15624==    by 0x47FFCD2: InsertShardPlacementRow (master_metadata_utility.c:429)      
==15624==    by 0x4802703: CreateShardPlacements (master_stage_protocol.c:391)          
==15624==    by 0x4802888: master_create_empty_shard (master_stage_protocol.c:130)      
==15624==    by 0x8237669: ExecMakeFunctionResultNoSets (execQual.c:2019)               
==15624==    by 0x823DCCE: ExecTargetList (execQual.c:5365)                             
==15624==    by 0x823DCCE: ExecProject (execQual.c:5580)                                
==15624==    by 0x8252D73: ExecResult (nodeResult.c:155)                                
==15624==    by 0x823643F: ExecProcNode (execProcnode.c:385)                            
==15624==    by 0x8232BF3: ExecutePlan (execMain.c:1549)                                
==15624==    by 0x8232BF3: standard_ExecutorRun (execMain.c:337)                        
==15624==    by 0x47F6C77: multi_ExecutorRun (multi_executor.c:201)                     
````

### PR DESCRIPTION
**Pull request by lithp**
Node port is defined as a bigint in the schema, but in `master_metadata_utility` (and everywhere else, really), we treat it as a uint32. This commit fixes the regression tests on 32-bit systems.

Closes #422 and closes #408

### CODE REVIEW

**Comment by anarazel** [comment]
Have you check the "everywhere else" bit for similar required changes?

**Comment by ozgune** [comment]
@lithp -- we originally assumed that node port was 32-bit. Could you look at this more comprehensively and also update #422?

**Comment by anarazel** [comment]
I think we should merge this (after rebasing), so we don't crash. That still allows us to do the proper solution with the schema change, but that's a lot more complex than just doing this.

**Comment by anarazel** [comment]
@sumedhpathak Are you ok with that?

**Comment by anarazel** [comment]
We're planning to merge this, to unblock debian packaging, which requires 32builds to work. We can then, for 5.1 or 5.2, still adjust the schema. I'm rebasing the branch so we can merge.

**Comment by sumedhpathak** [comment]
I am. Could we note this in the other Issue, so we can track that these two lines will need to be changed to 32-bit accessors again after we alter the metadata?

**Comment by anarazel** [comment]
I did a quick scan through the source-code without finding grave 32bit issues (a few printfs/elogs need different types, but it's harmless in practice), and ran all tests without errors. So I'm giving this a :shipit:

**Pull request merged**
