### PR TITLE
Update regression tests where metadata edited manually

### LINKED ISSUE #302: Update regression tests to master_create_distributed_table(..., 'hash') where appropriate
Our previous CREATE TABLE (...) DISTRIBUTE BY() syntax didn't allow for hash partitioned tables. With the changes in extensify-20, we can now create hash partitioned tables.

We have 4 regression tests where we manually convert an append partitioned table into a hash partitioned one. In 3 of these tests, we should instead use the new syntax for hash partitioned tables.

An easy way to find these tests is by grepping the following:

``UPDATE pg_dist_partition SET partmethod = 'h' ...``

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #302

Since our previous syntax did not allow creating hash partitioned tables,
some of the previous tests manually changed partition method to hash to
be able to test it. With this change we remove unnecessary workaround and
create hash distributed tables instead.

Besides since we create new shards, some hard-coded
shard ids from other tests were affected.

### CODE REVIEW

**Comment by anarazel** [comment]
I'm not a big fan of adding/using more generated files, they're a pain to maintain.  Don't we have copy tests already elsewhere? And why were the new tests added in a relatively unrelated commit, without being mentioned?

**Comment by byucesoy** [comment]
We have copy tests, some of the tables using in this test does not appear in copy tests but we can add that table to copy tests so that we don't need to generate files for this test.

There is no new tests added with this commit. I just created new tables with hash distribution instead of creating append distributed tables and manually set their partition method. Since I removed static files and move their content to test generating files, it looks like I added new tests, but I didn't.

If we decide to move data loading logic to copy tests, we don't need new generated files. What do you suggest?

**Comment by anarazel** [comment]
On 2016-05-18 05:27:00 -0700, Burak Yücesoy wrote:
> There is no new tests added with this commit. I just created new
> tables with hash distribution instead of creating append distributed
> tables and manually set their partition method. Since I removed static
> files and move their content to test generating files, it looks like I
> added new tests, but I didn't.

Uh, something's not right here then. The diff shows no removed \copy
calls (did you perhaps not remove one file?), but added ones.

**Comment by byucesoy** [comment]
It appears that, I don't need to copy any data at all. I thought do not loading data may cause change in plan. However this is not the case with hash distribution. It was my mistake.

So as a result, no need for generated files and additional copy. I sent new patch.

**Comment by metdos** [comment]
Hey @anarazel , would you like to be the official reviewer of this PR because you commented on this and it's very small. If you don't have time, that's okay, we will review it here in Istanbul office.

**Comment by anarazel** [comment]
@metdos Signed myself up.

**Comment by anarazel** [comment]
Hm. This does not appear to actually fix all of the occurances of that pattern?  Why not do all of them in one swoop?

**Comment by byucesoy** [comment]
I sent a fix for one remaining manual change of partition method to hash. Apart from that, there are couple of manual changes of partition method to range.  Do you think we should also fix them in this PR?

**Comment by anarazel** [comment]
@byucesoy Yes, I think it makes sense to deal with them in one PR.

**Comment by byucesoy** [comment]
I started fixing manual changes of partition method to range. One of them is in `multi_distribution_metada.sql,` where we have a hash partitioned table and we change its partition method to range for some tests.

However metadata of hash distributed table is also created manually. It looks like this;

`-- create table to be distributed
CREATE TABLE events_hash (
	id bigint,
	name text
);

-- for this table we'll "distribute" manually but verify using function calls
INSERT INTO pg_dist_shard
	(shardid, logicalrelid, shardstorage, shardminvalue, shardmaxvalue)
VALUES
	(1, 'events_hash'::regclass, 't', '0', '10'),
	(2, 'events_hash'::regclass, 't', '10', '20'),
	(3, 'events_hash'::regclass, 't', '20', '30'),
	(4, 'events_hash'::regclass, 't', '30', '40');

INSERT INTO pg_dist_shard_placement
	(nodename, nodeport, shardid, shardstate, shardlength)
VALUES
	('cluster-worker-01', 5432, 1, 0, 0),
	('cluster-worker-01', 5432, 2, 0, 0),
	('cluster-worker-02', 5433, 3, 0, 0),
	('cluster-worker-02', 5433, 4, 0, 0),
	('cluster-worker-03', 5434, 1, 1, 0),
	('cluster-worker-03', 5434, 2, 1, 0),
	('cluster-worker-04', 5435, 3, 1, 0),
	('cluster-worker-04', 5435, 4, 1, 0);`

I am inclined to fix them also but I am not sure if this table was created in this way intentionally, because creating metadata in this way has some beneficial side effects (like being able to set shardstate, shardminvalue, shardmaxvalue)

I also talked with @metdos and we have 2 different options here;

1-) Keep creation of hash distributed tables in this way and create new range distributed tables with same way (i.e. create metadata manually)
2-) Create hash distributed table with `master_create_distributed_table` and `master_create_worker_shards` then modifying `shardstate` of particular columns. Create range distributed table with `master_create_distributed_table` and `master_create_empty_shard`.

I think option 2 is better way to do it but I am not sure whether these tables created in this way intentionally or because `master_create_distributed_table` was not available for hash tables at the moment.

**Comment by anarazel** [comment]
I agree that 2) is a better option.

> but I am not sure whether these tables created in this way intentionally or because master_create_distributed_table was not available for hash tables at the moment.

master_create_distributed_table didn't yet exist back then.

**Comment by byucesoy** [comment]
I also fixed the tests with manual creation of metadata. During the process, I had to change some hard-coded shard ids. Therefore it looks like 15 files were modified but most of them are not related with this change.

There are still some manual insertions to `pg_dist_shard` and `pg_dist_shard_placement` but I think they are not related with this problem.

**Comment by byucesoy** [comment]
@anarazel Do you think we can ship it now?

**Comment by anarazel** [comment]
Could you squash those two commits together and rebase? There doesn't appear to be a meaningful separation between the commits.  It's possible that a couple of conflicts have been introduced since.

**Comment by anarazel** [comment]
Other than that I think this is ready to go.

**Pull request merged**
