### PR TITLE
Omit public schema from shard_name output

### PR DESCRIPTION
**Pull request by marcocitus**
@samay-sharma does this work for fixing #1663?

### CODE REVIEW

**Comment by metdos** [comment]
@samay-sharma any comments on this?

**Comment by samay-sharma** [comment]
@marcocitus : Wanted to clarify on the behavior on %I. Does this mean that %I will work with all tables?

i.e. If there is a public schema, it'll not add the public that hence it'll work. Also, if there is a schema then it'll still work with the right schema.

If that's the behavior, then it looks good to me. Otherwise, could you clarify the behavior on %I?

**Comment by marcocitus** [comment]
> i.e. If there is a public schema, it'll not add the public that hence it'll work. Also, if there is a schema then it'll still work with the right schema.

No, the underlying `format` function does not quote schema names separately, unfortunately. If there is a schema, it will be encoded as `"myschema.mytable"`, which will throw an error. We could implement our own format function, but that'll be 1-2 weeks of work.

This PR unbreaks existing usages of `run_command_on_*` within the `public` schema, to avoid breaking applications of users that upgrade.

**Comment by furkansahin** [comment]
@samay-sharma if you are fine with this solution, the PR looks good to me.

**Comment by jasonmp85** [comment]
> We could implement our own format function, but that'll be 1-2 weeks of work.

I still think it wouldn't be terribly hard to add our own format modifier that means "replace this token with quoted-schema-dot-quoted-relation". We'd just scan for it and replace it with `%I.%I` and then use the typical format method to supply schema, relation name.

This could preserve existing behavior while providing a way forward for users who always want `"schema"."relationname"` behavior. one–two weeks for that improvement seems a high estimate.

**Comment by samay-sharma** [comment]
hey @marcocitus : Hmm. So, to summarize, %I would work for public schemas (i.e. existing %I usage would still work) but for tables in another schema we'd tell users to use %s. And that would schema qualify the table names.

If this is accurate, then it sounds fair to me. We can merge this PR and then update the docs and ask users with schemas to use %s. We can also add such an example to that section.

**Comment by marcocitus** [comment]
> I still think it wouldn't be terribly hard to add our own format modifier that means "replace this token with quoted-schema-dot-quoted-relation". We'd just scan for it and replace it with %I.%I and then use the typical format method to supply schema, relation name.

Some users have scripts that use syntax like `%1$s` to be able to refer to the shard name in multiple places. I think it makes sense to come up with our own format (maybe $shardname?), but it probably requires some careful design and we need to make sure not to break everyone's hacky scripts.

**Comment by marcocitus** [comment]
> Hmm. So, to summarize, %I would work for public schemas (i.e. existing %I usage would still work) but for tables in another schema we'd tell users to use %s. And that would schema qualify the table names.

Correct. You should also use %s if your table name contains strange characters, otherwise quotes will get added twice, but that's probably not super common.

**Comment by metdos** [comment]
@marcocitus shall we merge this?

**Pull request merged**
