### PR TITLE
Log username in the failed connection message

### PR DESCRIPTION
**Pull request by crabhi**
DESCRIPTION: Log username in the failed connection message

I hit this problem when I tried to do `citus_move_shard_placement(...)` and I didn't understand why it was failing with `fe_sendauth: no password supplied`. Turned out it tried to connect as a user I didn't expect.

This patch includes the username in the reported error message.

```
monitora_snapshot=# SELECT citus_move_shard_placement(102030, 'monitora.db-dev-worker-a', 6005, 'monitora.db-dev-worker-a', 6017);
ERROR:  connection to the remote node monitora_user@monitora.db-dev-worker-a:6017 failed with the following error: fe_sendauth: no password supplied
Time: 40,198 ms
```

### CODE REVIEW

**Comment by crabhi** [comment]
@microsoft-github-policy-service agree

**Comment by crabhi** [comment]
Running `make check` in a devcontainer runs 177 tests (successfully). But I see there are more "expected output" files that should be affected.

```
grep -R 'connection to the remote node' src/test/regress/expected/ | wc -l
184
```

What am I missing?

**Comment by crabhi** [comment]
I see this error in the output. So Make actually tries to run more tests but it can finish only one job.

```
cannot remove directory for tmp_check/ts0: No such file or directory at /workspaces/citus/src/test/regress/pg_regress_multi.pl line 643.
Could not remove tablespace directory at /workspaces/citus/src/test/regress/pg_regress_multi.pl line 643.
make: *** [Makefile:162: check-multi-1] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by crabhi** [comment]
Solved - the problem was caused by the devcontainer's `MAKEFLAGS=-j8`. Running the tests sequentially works OK.

**Comment by crabhi** [comment]
OK, so I've checked locally in devcontainer all tests I could make to run (apart from `check-citus-upgrade-*` and `check-enterprise-failure` I think). It's quite consuming without the CI parallelization.

Let's see what the CI jobs tell and I'll fix the rest.

**Comment by JelteF** [comment]
>  It's quite consuming without the CI parallelization.

Yeah running the full test suite locally is definitely not something that we do often. We depend a lot on CI to make it fast. And the use `run_test.py` to run the failing tests locally.

**Comment by JelteF** [comment]
Okay, it seems you caught all of them except the file `citus/citus/src/test/regress/expected/local_shard_execution_0.out` (which is a PG14 specific output file). 

You can ignore the "Test flakyness" failures, it's a false positive here and that test needs a slight modification to pass the tests.

**Comment by crabhi** [comment]
OK, then. Fixed `local_shard_execution_0.out`.

**Review by JelteF — APPROVED** [review]

**Pull request merged**
