### PR TITLE
Add citus_schema_move() function

### PR DESCRIPTION
**Pull request by onurctirtir**
Add citus_schema_move() that can be used to move tenant tables within a distributed
schema to another node. The function has two variations as simple wrappers around
citus_move_shard_placement() and citus_move_shard_placement_with_nodeid() respectively.
They pick a shard that belongs to the given tenant schema and resolve the source node
that contain the shards under given tenant schema. Hence their signatures are quite
similar to underlying functions:

```sql
-- citus_schema_move(), using target node name and node port
CREATE OR REPLACE FUNCTION pg_catalog.citus_schema_move(
	schema_id regnamespace,
	target_node_name text,
	target_node_port integer,
	shard_transfer_mode citus.shard_transfer_mode default 'auto')
RETURNS void
LANGUAGE C STRICT
AS 'MODULE_PATHNAME', $$citus_schema_move$$;

-- citus_schema_move(), using target node id
CREATE OR REPLACE FUNCTION pg_catalog.citus_schema_move(
	schema_id regnamespace,
	target_node_id integer,
	shard_transfer_mode citus.shard_transfer_mode default 'auto')
RETURNS void
LANGUAGE C STRICT
AS 'MODULE_PATHNAME', $$citus_schema_move_with_nodeid$$;
```

DESCRIPTION: Add citus_schema_move() function that can be used to move tenant tables within a distributed schema to another node.

- [x] Add tests

### CODE REVIEW

**Comment by onurctirtir** [comment]
Flaky test failure is a bit strange, looking into that.

**Comment by onurctirtir** [comment]
> Flaky test failure is a bit strange, looking into that.

The failure reported by flaky test detection job can be reproduced by running the following script three times quickly.
The following script also shows that the failure is not about the UDFs introduced in this PR but a race condition that happens in `TransferShards()` when cleaning orphaned resources up:

```sql
SET client_min_messages TO WARNING;
DROP SCHEMA IF EXISTS s1 CASCADE;

SET citus.next_shard_id TO 2220000;
SET citus.shard_replication_factor TO 1;

SET client_min_messages TO WARNING;
SELECT 1 FROM citus_add_node('localhost', 9700, groupid => 0);
SELECT master_set_node_property('localhost', 9700, 'shouldhaveshards', true);

SET client_min_messages TO NOTICE;

CREATE SCHEMA s1;
CREATE TABLE s1.t1 (a int);
SELECT create_distributed_table('s1.t1', null);

-- this is problematic at the third full run
WITH shardid_and_current_nodeport_cte AS(
    SELECT shardid, nodeport FROM citus_shards WHERE table_name = 's1.t1'::regclass
)
SELECT citus_move_shard_placement(shardid_and_current_nodeport_cte.shardid, 'localhost', shardid_and_current_nodeport_cte.nodeport, 'localhost', new_nodeport_subquery.nodeport, 'block_writes')
FROM (
    SELECT nodeport FROM (
        SELECT nodeport FROM pg_dist_node
        WHERE noderole = 'primary' AND isactive AND shouldhaveshards AND groupid != 0
        EXCEPT
        SELECT nodeport FROM shardid_and_current_nodeport_cte
    ) q
    LIMIT 1
) new_nodeport_subquery, shardid_and_current_nodeport_cte;

WITH shardid_and_current_nodeport_cte AS(
    SELECT shardid, nodeport FROM citus_shards WHERE table_name = 's1.t1'::regclass
)
SELECT citus_move_shard_placement(shardid_and_current_nodeport_cte.shardid, 'localhost', shardid_and_current_nodeport_cte.nodeport, 'localhost', new_nodeport_subquery.nodeport, 'block_writes')
FROM (
    SELECT nodeport FROM (
        SELECT nodeport FROM pg_dist_node
        WHERE noderole = 'primary' AND isactive AND shouldhaveshards AND groupid != 0
        EXCEPT
        SELECT nodeport FROM shardid_and_current_nodeport_cte
    ) q
    LIMIT 1
) new_nodeport_subquery, shardid_and_current_nodeport_cte;
```

Seems that second run of the script leaves an entry in `pg_dist_cleanup` for a moment. And if we do the third run very quickly, then `TransferShards()` both yields the following error and causes the shard placement table to disappear from the cluster:

```sql
WARNING:  relation "s1.t1_2220000" does not exist
ERROR:  cannot get the size because of a connection error

select result FROM run_command_on_all_nodes($$select array_agg(relname) from pg_class where relnamespace = 's1'::regnamespace$$);
┌────────┐
│ result │
├────────┤
│ {t1}   │
│ {t1}   │
│ {t1}   │
└────────┘
(3 rows)

-- normally we should see the shard rel in one of the nodes, as in:
-- ┌─────────────────┐
-- │     result      │
-- ├─────────────────┤
-- │ {t1,t1_2220000} │
-- │ {t1}            │
-- │ {t1}            │
-- └─────────────────┘
-- (3 rows)
```

**Review by marcocitus — COMMENTED** [review]
This looks fine to me, any comments on naming from @mulander ?

**Comment by onurctirtir** [comment]
> In summary, this happens only if we use the same shard-id when re-creating shard of the same distributed table on another worker node. For this reason, I feel like it should be ok with waiting until all pg_dist_cleanup records to expire before creating the distributed tables in this test file.

Done

**Comment by marcocitus** [comment]
> Done with the last commit.

is this pointing to an actual bug, or is it too synthetic in tests?

**Comment by JelteF** [comment]
> is this pointing to an actual bug, or is it too synthetic in tests?

It's because of reuse of the shard ids due to rerunning with `SET citus.next_shard_id TO 2220000;`.

**Review by marcocitus — APPROVED** [review]
The losing shards when changing next_shard_id is slightly concerning, but anyway not this PR's fault.

**Pull request merged**
