### PR TITLE
Add META.json for PGXN distribution.

### PR DESCRIPTION
**Pull request by theory**
All you have to do to release it on PGXN is zip up the distribution with this file. Edit its contents as appropriate. There's already a [citusdata](http://pgxn.org/user/citusdata) account to use to release it via [PGXN Manager](http://manager.pgxn.org/).

### CODE REVIEW

**Comment by ozgune** [comment]
@sumedhpathak -- who is the best person to review this pull request?

**Comment by citus-github** [comment]
Hi @theory, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://cla.citusdata.com).

**Comment by lfittl** [comment]
@theory I wanted to apologize for our slow response on this PR - we appreciate the contribution. Once the CLA is signed @jasonmp85 can proceed with the code review.

**Comment by theory** [comment]
Will sign as soon as I get the email.

**Comment by theory** [comment]
Paragraph 3 should be revised to explicitly license only those patents that are reflected in the contributions, not all patents owned by contributor.

**Comment by theory** [comment]
Signed.

**Comment by citus-github** [comment]
You did it @theory!

Thank you for signing the Citus Data Contributor License Agreement. We can now accept this contribution and all future contributions from you.

Somebody from our team will proceed with code review.

**Comment by lfittl** [comment]
@theory Thats good feedback - I'll check with legal to see if we can revise the document. Appreciate your help!

**Comment by jasonmp85** [comment]
Hey @theory,

I'm looking over this and since we've got all our packaging-related metadata files in the [citusdata/packaging](https://github.com/citusdata/packaging) repo, I'm inclined to start a `pgxn` branch there with a script to build and release the PGXN package.

Do you mind if I apply your patch to that repository instead? I suppose there's the (minor?) issue that that repo is Apache licensed, so I figured I'd ask ahead of time. I'll retain authorship information.

When we do our releases, we'll mostly be modifying files in that repo, which contains our Red Hat and Debian metadata files for packaging. It'll be easiest to remember to bump all the files there.

**Comment by theory** [comment]
Not at all, go for it.

**Comment by jasonmp85** [comment]
Alright, @theory… I've created a [`pgxn-citus` branch](https://github.com/citusdata/packaging/tree/pgxn-citus) in our packaging repo, where your commit lives on as citusdata/packaging@14699ae3ac0f572c42e5f9d29cfd4ee402d7e62b.

Since the metadata file lives in a separate repo, there is no need for a `5.0.2` release to include it, so I've reverted it to `5.0.1`. citusdata/packaging@438312817f244d66a1e00572b2635855825848af has the other (minor) change I made (such as marking myself as packaging maintainer).

For easily building this package (though it's essentially only "download the release tarball, unarchive it, add `META.json`, rearchive with proper name), I added a [PGXN build image](citusdata/packaging#6) to our build matrix as well as support for the [PGXN platform](citusdata/tools#6) to our `citus_package` tool.

I've tested the whole workflow, and all my coworkers should be able to build the latest PGXN artifact with a simple `citus_package -p pgxn citus release` (this form is to support e.g. `cstore_fdw` and any other OSS packages later as well).

Thanks for the nudge for us to do this! Closing this issue now since the commit has been pushed elsewhere. I need to finish a little work on our nightly/release buildboxen, then I'll generate 5.0 and 5.1 artifacts to push to PGXN.

**Comment by theory** [comment]
Huh, was curious about your build image and build platform links, but they 404, sadly.

So, when can I expect to see cities on PGXN? :-D

**Comment by jasonmp85** [comment]
> Huh, was curious about your build image and build platform links, but they 404, sadly.

Oops. I had repo/user issue links in my Markdown and it reads them as relative links. Fixed.

> So, when can I expect to see Citus on PGXN? :-D

Probably today.

**Comment by jasonmp85** [comment]
Just stopping by to say Citus 5.0.1 is now in PGXN. I uploaded it manually but added a Travis job that'll do it automatically from now on ([here it is running unnecessarily](https://travis-ci.org/citusdata/packaging/builds/135094188)).

I'm about to go around and bump all our build files to 5.1, at which point you'll see an upload for 5.1. Thanks!

**Comment by theory** [comment]
[Awesome](https://twitter.com/pgxn/status/738782580993052672), thanks!

**Pull request closed without merging**
