### PR TITLE
Move C files into the appropriate directories

### PR DESCRIPTION
**Pull request by marcocitus**
Super minor thing that keeps bugging me.

### CODE REVIEW

**Comment by serprex** [comment]
Somewhat related: what's going on with the header file layout? Feels like for the most part they exist in a flat `include/distributed/header.h` but now some are existing in subdirectories. Is it desirable that header files should exist in a subdirectory matching the subdirectory they exist in in backend?

**Comment by serprex** [comment]
codecov issue is because this needs to be updated: https://github.com/citusdata/citus/blob/622ee54c95c172ca54047d296f69d440910cd3d4/.codecov.yml#L11

**Comment by marcocitus** [comment]
> Is it desirable that header files should exist in a subdirectory matching the subdirectory they exist in in backend?

I think yes.

**Comment by serprex** [comment]
@marcocitus you never addressed my note about `.codecov.yml`

**Comment by marcocitus** [comment]
> @marcocitus you never addressed my note about .codecov.yml

oops, fixed it on master

**Pull request merged**
