### PR TITLE
Remove failing assertions

### PR DESCRIPTION
**Pull request by agedemenli**
DESCRIPTION: Fix assertion crash for maintenance daemon

The extension is dropped, which calls StopMaintenanceDaemon which removes the MaintenanceDaemonDBData from MaintenanceDaemonDBHash and sends a kill signal, but that does not actually stop the maintenance daemon immediately. If the maintenance daemon had just entered InitializeMaintenanceDaemonBackend when the extension was being dropped, it would no longer see the entry in the hash

fixes: #4321

### CODE REVIEW

**Review by pykello — APPROVED** [review]
Can you add some detailed explanation on what was the circumstances these assertions were not held?

**Comment by onurctirtir** [comment]
I think we shouldn't have a description entry for this pr

**Comment by agedemenli** [comment]
> I think we shouldn't have a description entry for this pr

makes sense, thank you

**Comment by agedemenli** [comment]
> I think we shouldn't have a description entry for this pr

Instead, I updated the description to be more suitable for the changelog. Could you please check it out?

**Comment by onurctirtir** [comment]
> > I think we shouldn't have a description entry for this pr
> 
> Instead, I updated the description to be more suitable for the changelog. Could you please check it out?

I thought this was already specific to citus 10.0, isn't it ?

**Pull request merged**
