### PR TITLE
nodeport int8 -> int4

### LINKED ISSUE #424: Consider changing nodeport type in pg_dist_shard_placement to int4
Currently, the type of nodeport in the pg_dist_shard_placement is int8, which should be int4.

Changing the type will require an version change with an upgrade script containing:
ALTER TABLE pg_dist_shard_placement ALTER COLUMN nodeport TYPE int4;

To upgrade, users need to install the new version and run:
ALTER EXTENSION citus UPDATE;

While using the wrong type is currently causing issues on 32-bit platforms (#422), there is a simple fix (#423) and it might be better to defer changing metadata until other metadata changes are required.

### PR DESCRIPTION
**Pull request by lithp**
Fix #424 (Based off PR #868, which must be merged in first)

This will, I believe, crash on 32-bit systems during the upgrade (if any queries come in between restart and upgrade). But 64-bit systems will upgrade just fine, even if the metadata tables are changed between restart and extension upgrade.

### CODE REVIEW

**Comment by jasonmp85** [comment]
This looks fine to me. I read every place in the code we read or write this struct field (and where those values go), and I think you're right that the sole remaining `int8` reference is in the catalog definition itself.

With all that said, why make this change? We're just swapping one too-big representation (`int8`) for another too-big representation (`int4`). Port numbers vary from `0` to `65535`, so ideally, we'd have an unsigned `int2` or something (though PostgreSQL does not provide that).

The purist in me says if we're going to change this, why not do `CREATE DOMAIN portnumber AS int4 CHECK (VALUE BETWEEN 0 AND 65535)`?

I realize our code won't actually enforce this most places (as I believe `simple_heap_insert` will skip that check), but it would be much better at declaring what we mean, and we could change our C code to use `uint16`.

**Comment by anarazel** [comment]
How's this not broken before the upgrade script has run?

**Comment by jasonmp85** [comment]
@anarazel I believe all that was discussed in #424, though I can't actually tell where the discussion landed :-P

**Comment by anarazel** [comment]
@jasonmp85 I don't see a careful discussion that applies to the current state. But even if there were, that information needs to be included in the commit message and such. Otherwise there's no way to later actually investigate problems.

**Comment by jasonmp85** [comment]
@anarazel do you have a quick solution? I'm not so worried about the upgrade script running (we could add a conditional to check and do the right thing based on what extension version is loaded, slow as that may be?) as I am about running the upgrade script without reloading the library. Is there a good  workaround?

**Comment by anarazel** [comment]
> @anarazel do you have a quick solution?

Yes. Don't do anything. The troubles here seem way higher than the
reward.


> I'm not so worried about the upgrade script running (we could add a
> conditional to check and do the right thing based on what extension
> version is loaded, slow as that may be?) as I am about running the
> upgrade script without reloading the library. Is there a good
> workaround?

I think we should, longer term, add error checks that prevent citus
usage if a) the library is newer than the extension b) the reverse. But
that's not entirely trivial, so we probably won't get to it this
release.

Andres

**Comment by anarazel** [comment]
So, if we want to change the code, we need to add the equivalent of:
```
	if (tupleDescriptor->attrs[Anum_pg_dist_shard_placement_nodeport -1]->atttypid == INT4OID)
		shardPlacement->nodePort = DatumGetInt32(nodePort);
	else
		shardPlacement->nodePort = DatumGetInt64(nodePort);
```
to nodePort accessors.

**Comment by lithp** [comment]
Okay, you two are super overthinking things!

**More descriptive commit message**: Good point, I should have already written this down.

**What happens between restart and upgrade**: Nothing will crash, because the code *already* treated it as a 32-bit number before we merged https://github.com/citusdata/citus/pull/423. That change was made to allow Citus to run on 32-bit systems. 64-bit systems will upgrade correctly, but 32-bit systems will experience a crash if queries are run before the metadata is migrated. This is *exactly* why I recommended not merging https://github.com/citusdata/citus/pull/423 in the first place... I don't believe we have anyone running Citus on 32-bit in production, are there even any 32-bit servers any more, so we can push out this new version with a big warning saying upgrades of 32-bit systems will require downtime?

**running the upgrade script without reloading the library**: @jasonmp85 in what situation would that happen? We can add a guard to the upgrade file that errors out if the correct version of the extension isn't running.

**Comment by anarazel** [comment]
@lithp It's not that simple, no.

 On 32bit platforms int4 is pass-by-value, but 64bit is pass-by-reference:
```
/*
 * DatumGetInt64
 *		Returns 64-bit integer value of a datum.
 *
 * Note: this macro hides whether int64 is pass by value or by reference.
 */

#ifdef USE_FLOAT8_BYVAL
#define DatumGetInt64(X) ((int64) GET_8_BYTES(X))
#else
#define DatumGetInt64(X) (* ((int64 *) DatumGetPointer(X)))
#endif
```
and
```
/*
 * Int64GetDatum
 *		Returns datum representation for a 64-bit integer.
 *
 * Note: if int64 is pass by reference, this function returns a reference
 * to palloc'd space.
 */

#ifdef USE_FLOAT8_BYVAL
#define Int64GetDatum(X) ((Datum) SET_8_BYTES(X))
#else
extern Datum Int64GetDatum(int64 X);
#endif
...
#ifndef USE_FLOAT8_BYVAL		/* controls int8 too */

Datum
Int64GetDatum(int64 X)
{
	int64	   *retval = (int64 *) palloc(sizeof(int64));

	*retval = X;
	return PointerGetDatum(retval);
}
#endif   /* USE_FLOAT8_BYVAL */
```

So by changing the .so but not the schema and/or the other way round you'll indeed cause trouble.

**Comment by anarazel** [comment]
(it's also the case on some other platforms, even 64bit ones)

**Comment by sumedhpathak** [comment]
@lithp Does Andres's comment help? The change proposed seems straightforward to add?

**Comment by lithp** [comment]
@anarazel @jasonmp85 (I'm not sure which of you are my reviewer) Take a look at this then.

I built a version of postgres with `--disable-float8-byval` and the tests generated a raft of errors. I've fixed the crashes but haven't managed to get the tests passing and they fail in strange ways. Since in practice we require `USE_FLOAT8_BYVAL` I made that explicit by adding a check to `./configure`, that should mean the upgrade will work just fine on a system if Citus compiles.

**Comment by anarazel** [comment]
On 2016-10-19 08:00:11 -0700, Brian Cloutier wrote:
> I built a version of postgres with `--disable-float8-byval` and the tests generated a raft of errors. I've fixed the crashes but haven't managed to get the tests passing and they fail in strange ways. Since in practice we require `USE_FLOAT8_BYVAL` I made that explicit by adding a check to `./configure`, that should mean the upgrade will work just fine on a system if Citus compiles.

We atm have 32bit builds in debian / ubuntu. Those have to run without
USE_FLOAT8_BYVAL as there's no general purpose 64bit registers.  So I
don't think that check is ok.

**Comment by lithp** [comment]
Okay, created a ticket to track the changes we'll have to make in order to support USE_FLOAT8_BYVAL and 32-bit in general: https://github.com/citusdata/citus/issues/891

**Comment by sumedhpathak** [comment]
Discussing with Andres and Ozgun, we decided to punt on this in favor of adding infrastructure to detect whether we have a version mismatch between the code and extension. Andres will drive this with Brian this week. For this change specifically, we decided to only fix the Index lookup equality operator, so it remains consistent with the DB representation of nodePort.

**Comment by anarazel** [comment]
Note there's a similar issue in ```NodeHasActiveShardPlacements``` where we currently use the functions for the wrong datatype:
```
	ScanKeyInit(&scanKey[1], Anum_pg_dist_shard_placement_nodeport,
				BTEqualStrategyNumber, F_INT4EQ, Int32GetDatum(nodePort));
```
these should, for the moment, really be INT8EQ and Int64Get.

**Comment by sumedhpathak** [comment]
@lithp Could we close this issue now? One follow-up was to update the Index equality operator, so do you know if we did that for 6.0? If so, let's go ahead and close this PR.

Thanks!

**Comment by lithp** [comment]
@sumedhpathak I assume you meant close the PR, and not the issue?

Yes, we changed the operator: https://github.com/citusdata/citus/pull/910/files

**Pull request closed without merging**
