### PR TITLE
Convert ExecuteRemoteCommand and ExecuteRemoteQuery to new connection api

### PR DESCRIPTION
**Pull request by mtuncer**
Convert ExecuteRemoteCommand and ExecuteRemoteQuery to new connection api.

This is a partial fix for  1101.

Conversions for
- master_expire_table_cache
- WorkerCreateShard

would be completed.

Shard rebalancer needs to call ExecuteRemoteCommand in Citus instead of its own version after this PR is merged.

### CODE REVIEW

**Comment by marcocitus** [comment]
> WorkerCreateShard

We should probably use GetPlacementConnection for that. Otherwise, a subsequent query on a newly created placement in the same transaction might not use the connection that was used to create the placement and would thus throw a strange error.

We might also want to use a separate connection per placement to allow COPY after a create_distributed_table in the same transaction. In fact this is critical for #1117 to work.

I also have some hesitations around how converting ExecuteRemoteQuery affects schema creation, see #1201.

**Comment by aamederen** [comment]
> I also have some hesitations around how converting ExecuteRemoteQuery affects schema creation, see #1201.

Yeah, we have attempted a similar thing in #1201 but after discussing with @marcocitus and @anarazel, we have decided to postpone it a further.

**Comment by anarazel** [comment]
On 2017-02-13 10:05:52 -0800, Eren Başak wrote:
> > I also have some hesitations around how converting ExecuteRemoteQuery affects schema creation, see #1201.
> 
> Yeah, we have attempted a similar thing in #1201 but after discussing with @marcocitus and @anarazel, we have decided to postpone it a further. 

Note that further was after the release, i.e. now ;)

**Comment by metdos** [comment]
@mtuncer, could you coordinate a meeting with @anarazel and @marcocitus next week, and decide how to move forward?

**Comment by metdos** [comment]
> We will also want to use a separate connection per placement to allow COPY after a create_distributed_table in the same transaction. This is critical for #1117 to work.

Hey @marcocitus, I started to look into this. Do we have an API for this, I think GetPlacementConnection() returns the same connection for different placements on the same machine.

**Comment by marcocitus** [comment]
It'll need to call `ClaimConnectionExclusively` like COPY does.

**Comment by marcocitus** [comment]
Superseded by #1436

**Pull request closed without merging**
