### PR TITLE
Makefile fix DESTDIR together with cleanup

### PR DESCRIPTION
**Pull request by JelteF**
DESCRIPTION: Fix Makefile trying to cleanup PG directory during install

This should fix this build issue: https://redmine.postgresql.org/issues/5032

### CODE REVIEW

**Comment by metdos** [comment]
@JelteF do we need to backport this to 9.1 release branch?

**Comment by JelteF** [comment]
If we do another 9.1 release I think it makes sense to include this as well, but doing 9.1.2 only for this seems not very useful. The workaround is very simple.

**Comment by metdos** [comment]
@JelteF I think you can cherry-pick this to 9.1 release branch. If we later decide to release another patch release it would be there.

**Comment by JelteF** [comment]
Done

**Comment by devrimgunduz** [comment]
Hi,

> If we do another 9.1 release I think it makes sense to include this as well, but doing 9.1.2 only for this seems not very useful. The workaround is very simple, i.e. run as `sudo` or remove citus files from your PG directory manually before.

Your use base prefer prebuilt packages. Building and patching the source file is not preferred. So, can I get a new point release, please, to build the RPMs?

Thx! Devrim

**Comment by JelteF** [comment]
@devrimgunduz We tagged a new version: 9.1.2

**Comment by devrimgunduz** [comment]
Hi @JelteF , already pushed them to the RPM repos. Thanks!

**Pull request merged**
