### PR TITLE
Ignore some am sql and out files

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**

### CODE REVIEW

**Comment by hanefi** [comment]
What is the reasoning behind ignoring these files that do not seem to be generated.

See #4811 for the tests that actually make sure that all the ignored `.sql` and `.out` files are generated from `.source` files. If you think that the logic in the script `ci/fix_gitignore.sh` needs improvement, feel free to update that script here.

**Comment by SaitTalhaNisanci** [comment]
These files exist in 10.0. They are generated files there and then they are renamed I think. They would sometimes appear in my local and that is why I thought of ignoring them

**Comment by hanefi** [comment]
The ignore rules on release branches are wrong, and master is fine. The reason is that #4811 merged to master after we created `release-10.0` and `release-10.1` branches.

I think that we should not have rules to ignore these files on master, but fix the underlying issue on relevant release branches.

**Comment by hanefi** [comment]
I think we should close this PR.

If you want, we can backport #4811 to `release-10.1` and `release-10.0` branches instead.

**Pull request closed without merging**
