### PR TITLE
Merge ruleutils_13.c and ruleutils_14.c into a single file

### PR DESCRIPTION
**Pull request by onurctirtir**
Thought that we could drop one of three ruleutils files by
making use of compile-time checks, in order to improve
maintainability of those copied files.

Given that we will anyway drop support for PG-12 soon (maybe
in Citus-11 ?), didn't bother doing the same for ruleutils_12.c.
Plus, seems that merging those three files is slightly harder
than merging only two.

How I made the changes is as follows:
* $ cp ruleutils_14.c ruleutils_13.c
* $ mv ruleutils_13.c ruleutils_13_14.c
* $ rm ruleutils_14.c
* use compile time macros to reflect both versions in ruleutils_13_14.c

### CODE REVIEW

**Comment by onderkalaci** [comment]
How is this going to impact the new version support? My impression was that we manage/reduce complexity by having a duplicate files. Would be good to discuss with broader team before merging, making sure that this wouldn't lead to increased maintenance for the long term.

I think it could make sense to discuss people worked on enabling pg12/pg13/pg14 and ask if this could have made things harder or not

**Comment by onurctirtir** [comment]
> My impression was that we manage/reduce complexity by having a duplicate files. 

I was thinking the same first, but then I realized that we anyway create ruleutils_{x}.c by copying ruleutils_{x-1}.c, not by copying up-to-date ruleutils.c from postgres.

So I thought that this could even make the process easier when the changes made on ruleutils.c file in postgres is not huge, given that we make the changes on ruleutils_{x}.c manually.

But yeah, it makes sense to discuss this with the broader team.

**Comment by onurctirtir** [comment]
I wonder what @halilozanakgul would think :), given that he is the person who added the latest ruleutils file for pg14 support.

**Review by halilozanakgul — CHANGES_REQUESTED** [review]
I see you haven't handled some comment and castNode->lfirst_node changes which are probably no problem. But I mainly wonder why we had these different ruleutils.c versions in the first place when we had the version control macros most places.

**Pull request closed without merging**
