### PR TITLE
remove the flag

### PR DESCRIPTION
**Pull request by furkansahin**
WIP

references #1806

### CODE REVIEW

**Comment by marcocitus** [comment]
Does this cause errors on startup if people still have the flag in their postgresopen.conf?

**Comment by onderkalaci** [comment]
> Does this cause errors on startup if people still have the flag in their postgresopen.conf?

It should :) We talked with @metdos and discussed that this is better for 7.3. We've been warning the users since 7.0.  Another option could be never remove this GUC and add a comment in the code?

**Comment by marcocitus** [comment]
We should only remove GUCs in major releases (8.0/PG11), since it requires upgrade steps.

**Comment by onderkalaci** [comment]
> We should only remove GUCs in major releases (8.0/PG11), since it requires non-standard upgrade steps.

I missed that... So, we should close this PR

**Comment by furkansahin** [comment]
This issue is postponed to major release.

**Pull request closed without merging**
