### PR TITLE
These tests often deadlock in travis, run them in series

### PR DESCRIPTION
**Pull request by lithp**

### CODE REVIEW

**Comment by marcocitus** [comment]
Can you give a sample output? This definitely doesn't seem like the right fix :).

**Comment by jasonmp85** [comment]
What's wrong with this as a fix? I've seen bad interactions between these two tests in Travis as well. I guess we could work to make them work in parallel, but this fixes the problem for now (important since we're about to branch).

**Comment by marcocitus** [comment]
These tests are definitely not supposed to deadlock. The right fix is to make sure there is no deadlock.

https://github.com/citusdata/citus/pull/1503 got merged after this PR was opened, so it's possible that this is no longer an issue.

I'd like to see a sample output generated from the current master branch before we do anything with this PR.

**Comment by marcocitus** [comment]
Haven't seen this happen, I think it was fixed by #1503.

**Pull request closed without merging**
