### PR TITLE
Add the ability to recursively plan tables & enable local-distributed table joins

### PR DESCRIPTION
**Pull request by onderkalaci**
The prototype adds the logic to recursively plan relations by pushing down the filters and projections to the subquery (and implements it for local-distributed table joins). It relies on Postgres to fetch the filters, meaning that filters via JOINs can be pushed down as well.
 
As the  first implementation, we can recursively plan local tables and enable local - distributed table joins.

```SQL
SELECT count(*) FROM distributed_table JOIN postgres_table USING(key) WHERE distributed_table.key = 1;
DEBUG:  Wrapping local relation "postgres_table" to a subquery: SELECT key, NULL::text AS value, NULL::jsonb AS value_2 FROM public.postgres_table WHERE (key OPERATOR(pg_catalog.=) 1) OFFSET 0 
DEBUG:  generating subplan 15_1 for subquery SELECT key, NULL::text AS value, NULL::jsonb AS value_2 FROM public.postgres_table WHERE (key OPERATOR(pg_catalog.=) 1) OFFSET 0
DEBUG:  Plan 15 query after replacing subqueries and CTEs: SELECT count(*) AS count FROM (public.distributed_table JOIN (SELECT intermediate_result.key, intermediate_result.value, intermediate_result.value_2 FROM read_intermediate_result('15_1'::text, 'binary'::citus_copy_format) intermediate_result(key integer, value text, value_2 jsonb)) postgres_table USING (key)) WHERE (distributed_table.key OPERATOR(pg_catalog.=) 1)

```

With this prototype, we can enable wide range of SQL coverage improvements
a.	Enables direct local table - distributed table joins
b.	Enables unsupported outer joins with reference tables/ctes/subqueries by recursively planning the inner parts of the queries (#2504)
c.	Could potentially enable almost full SQL coverage via pull-push execution (e.g., naïve way is to keep recursively planning tables until the query is plannable by Citus).

The caveat is that all the performance characteristics of the pull-push execution applies to recursive planning of the relations. And, relations can be huge, even if we push filters and projections. The reason that I started with (a) is that local tables are likely to be much smaller, so pull-push execution can be acceptable (or even desired). For (b) and (c), recursive planning might not be the best option, given that the data sizes might be huge, so proper repartitioning between the worker nodes is probably more desirable. 
 
For (b), I already had a prototype and it could potentially work reasonably well. For (c), even if we want to go that route, we should probably first invest other parts. First, the planner should have some statistics so that it can pick the most optimal relations to recursively plan. Second, we should improve the intermediate result infrastructure in two ways: (i) Implement  Partitioned “broadcast” (ii) Improve intermediate results by using Custom scans (iii) any other improvements for intermediate results such as adjusting the cost well

### CODE REVIEW

**Comment by onderkalaci** [comment]
I guess finding a representative case is not that easy. Instead of using random table/data, I used tpch schema with custom queries and scale factor 10. For reference tables nation/region/supplier tables, I used local tables equivalents as well. If you have any more test ideas, let me know!

Overall, the performance seems %30-%40 worse compared to reference table case. The  difference mostly seem to boil down joins with intermediate results not performing very well.

The data size:
```SQL
 select count(*) from lineitem ;
  count   
----------
 59986052
(1 row)

Time: 1015.685 ms (00:01.016)
pguser=# select count(*) from supplier;
 count  
--------
 100000
(1 row)

Time: 7.913 ms
pguser=# select count(*) from nation;
 count 
-------
    25
(1 row)

Time: 2.217 ms
pguser=# 
```


```SQL
select count(*) from lineitem,supplier WHERE l_suppkey = s_suppkey;
  count   
----------
 59986052
(1 row)

Time: 3355.616 ms (00:03.356)

select count(*) from lineitem,supplier_local WHERE l_suppkey = s_suppkey;
  count   
----------
 59986052
(1 row)

Time: 5064.332 ms (00:05.064)


=================

select count(*) from lineitem, supplier, nation WHERE l_suppkey = s_suppkey AND s_nationkey = n_regionkey ;

  count   
----------
 59896200
(1 row)

Time: 2984.533 ms (00:02.985)


select count(*) from lineitem, supplier_local, nation_local WHERE l_suppkey = s_suppkey AND s_nationkey = n_regionkey ;

  count   
----------
 59896200
(1 row)

Time: 4568.464 ms (00:04.568)



============
select count(*) from lineitem, orders, supplier, nation WHERE o_orderkey = l_orderkey AND l_suppkey = s_suppkey AND s_nationkey = n_regionkey ;
  count   
----------
 59896200
(1 row)

Time: 6884.617 ms (00:06.885)


select count(*) from lineitem, orders, supplier_local, nation_local WHERE o_orderkey = l_orderkey AND l_suppkey = s_suppkey AND s_nationkey = n_regionkey ;

  count   
----------
 59896200
(1 row)

Time: 11509.585 ms (00:11.510)
```

**Comment by onderkalaci** [comment]
> The difference mostly seem to boil down joins with intermediate results not performing very well.

For example, the expected rows vs actual rows have a really big difference for hash-join when intermediate results are used: https://explain.depesz.com/s/oELQ

**Comment by marcocitus** [comment]
> select count(*) from lineitem, supplier_local, nation_local WHERE l_suppkey = s_suppkey AND s_nationkey = n_regionkey ;

Can you add this for lineitem_local? That seems like the base case.

**Comment by onderkalaci** [comment]
|lineitem  | nation | supplier| execution time|
| ------------- | ------------- |------------- |------------- |
| local  | local  | local  | 5669.059 ms  
| distributed  | local  | local  | 11509.585 ms
| distributed  | reference  | reference  | 2984.533 ms
| local  | reference  | reference  | 181615.281 ms (bad planning*)
| local  | reference  | reference  | 24616.978 ms ms (good planning**)





I hope that users wouldn't pick lineitem as the local one :) (* )With this, the difference is significant:
```SQL

select count(*) from lineitem_local, supplier, nation WHERE l_suppkey = s_suppkey AND s_nationkey = n_regionkey ;
  count   
----------
 59896200
(1 row)

Time: 181615.281 ms (03:01.615)
```

** However, if the planner were to be a little smarter -- which I hope to get within the PR --, and had chosen `"pull-distributed"` mode, the difference again boils down mostly to the performance of intermediate table joins:
```SQL
set citus.local_table_join_policy TO "pull-distributed" ;
SET
Time: 0.393 ms
 select count(*) from lineitem_local, supplier, nation WHERE l_suppkey = s_suppkey AND s_nationkey = n_regionkey ;
  count   
----------
 59896200
(1 row)

Time: 24616.978 ms (00:24.617)

```

**Comment by onderkalaci** [comment]
superseded by https://github.com/citusdata/citus/pull/4358

**Pull request closed without merging**
