### PR TITLE
Set Explicit ShardId/JobId In Regression Tests

### LINKED ISSUE #271: Set shardid / jobid sequence explicitly in regression tests before staging data.
Currently, whenever we add regression tests it messes up those tests which have explicit shard ids or job ids within them. If we explicitly set shard id and job id sequences, then we don't have to update the shard / job ids every time we add more queries or stage more data.

### PR DESCRIPTION
**Pull request by aamederen**
Fixes #271

This change sets ShardIds and JobIds for each test case. Before this change,
when a new test that somehow increments Job or Shard IDs is added, then
the tests after the new test should be updated.

ShardID and JobID sequences are set at the beginning of each file with the
following commands:

```
ALTER SEQUENCE pg_catalog.pg_dist_shardid_seq RESTART 290000;
ALTER SEQUENCE pg_catalog.pg_dist_jobid_seq RESTART 19000;
```

ShardIds and JobIds are multiples of 10000. Exceptions are:
- `multi_large_shardid`: shardid and jobid sequences are set to much larger values
- `multi_fdw_large_shardid`: same as above
- `multi_join_pruning`: Causes a race condition with multi_hash_pruning since
they are run in parallel.

### CODE REVIEW

**Comment by jasonmp85** [comment]
LOL "CLA Signed"? @lfittl?

**Comment by lfittl** [comment]
@jasonmp85 I'll look into it - the checks can be a bit weird, I think it has to do with @aamederen's team membership (seen it before and thought it was fixed).

In any case, this would only produce unnecessary "CLA Signed" - checks for external contributors are fine.

**Comment by jasonmp85** [comment]
> In any case, this would only produce unnecessary "CLA Signed" - checks for external contributors are fine.

Yeah, I figured as much. 😛

That said, if we had better management of our GitHub teams (we're the only org members, external contributor for all else), it would make that distinction clearer; however, that way lies higher billing, I think.

**Comment by onderkalaci** [comment]
couldn't we simply make both shardid and jobid be within the same range for a single file?
i.e.,

```
ALTER SEQUENCE pg_catalog.pg_dist_shardid_seq RESTART 290000;
ALTER SEQUENCE pg_catalog.pg_dist_jobid_seq RESTART 290000;
```
So that we can add new test files easier?

**Comment by mtuncer** [comment]
@onderkalaci  I like this idea. I will reduce having a separate search for next jobid, shardid into a single search for the newly added test.

**Comment by mtuncer** [comment]
since there is a magnitude of difference we could also go for jobId = shardId / 10 approach. more like

```
ALTER SEQUENCE pg_catalog.pg_dist_shardid_seq RESTART 290000;
ALTER SEQUENCE pg_catalog.pg_dist_jobid_seq RESTART 29000;
```

**Comment by aamederen** [comment]
ShardIDs and JobIDs are same now.

**Comment by mtuncer** [comment]
looks good :ship:

**Pull request merged**
