### PR TITLE
Introduce placement IDs.

### PR DESCRIPTION
**Pull request by anarazel**
So far placements were assigned an Oid, but that was just used to track
insertion order. It also did so incompletely, as it was not preserved
across changes of the shard state. The behaviour around oid wraparound
was also not entirely as intended.

The newly introduced, explicitly assigned, IDs are preserved across
shard-state changes.

The prime goal of this change is not to improve ordering of task
assignment policies, but to make it easier to reference shards.  The
newly introduced UpdateShardPlacementState() makes use of that, and so
will the in-progress connection and transaction management changes.

TODO:  Some of the regression test output changes need to be verified more
carefully. It looks like they're all due to preserving due to preserving
the original creation order now, but making sure of that would be good.

### CODE REVIEW

**Comment by marcocitus** [comment]
:ship:

**Comment by onderkalaci** [comment]
@anarazel @marcocitus 
We've a question with @byucesoy.

Now that the `UpdateShardPlacement` logic is added to preserve the placement id on the state changes. 

Looking into `master_copy_shard_placement`, which is used to repair shard, does not obey this. Once we repair a shard, we generate a new id. 
(Note that repair function calls `DeleteShardPlacementRow`, then `CreateShardPlacements` which generates a new id.)

Is that the expected behaviour? In the shard rebalancer PR, we're changing so that repair preserves the placement id. Any objections?

**Comment by byucesoy** [comment]
@anarazel @marcocitus 
We've another question with @onderkalaci 

We sort active placements by placementId in ActiveShardPlacementLists function. However router planner does not use this function to generate worker list and that list is not sorted by placementId. Should we also sort worker list by placementId for router planner queries?

We encountered with this problem in multi_repair_shard test after fixing the issue @onderkalaci mentioned in shard rebalancer PR. In that test;

- We have a table with 1 shard, 2 replicas.
- We create artificial placement in pg_dist_shard_placement for that single shard.
- We update shard state of original two placements, so PostgreSQL re-creates them with bigger oid.
- We run a query, it goes to artifical placement since its oid is smallest now. (and gives warning because it is not real placement)

**Comment by marcocitus** [comment]
> Is that the expected behaviour? In the shard rebalancer PR, we're changing so that repair preserves the placement id. Any objections?

Nope, you can and probably should use UpdateShardPlacement. Moving should always generate a new placement ID.

> Should we also sort worker list by placementId for router planner queries?

Preferably, the placements should be sorted by node ID, or some consistent worker order.  This would address #861.

**Comment by onderkalaci** [comment]
> Nope, you can and probably should use UpdateShardPlacement. Moving should always generate a new placement ID.

Yes, we did that. Just a clarification on certain UDFs, for both replicate and rebalance UDF's, we created new placementIds, for repair UDF we used `UpdateShardPlacement`

**Pull request merged**
