### PR TITLE
Get reproducible costs between different PostgreSQL versions

### PR DESCRIPTION
**Pull request by metdos**

### CODE REVIEW

**Comment by lithp** [comment]
I guess this is to make tests happy?

**Comment by metdos** [comment]
> I guess this is to make tests happy?

Yeap.

**Comment by anarazel** [comment]
Looks good, but did you, locally, run a full check? Because IIRC travis still doesn't quite run everything (e.g. the MX tests).

**Comment by metdos** [comment]
> Looks good, but did you, locally, run a full check? Because IIRC travis still doesn't quite run everything (e.g. the MX tests).

Yes, locally I run a full check.

Travis also runs a full check via
```
make check
```

which is equal to
```
check: check-full
```

**Comment by anarazel** [comment]
Great, then: :shipit:

**Pull request merged**
