### PR TITLE
Window function pushdown support

### PR DESCRIPTION
**Pull request by furkansahin**
WIP

### CODE REVIEW

**Comment by marcocitus** [comment]
Quick question: Are we also planning to implement non-pushdownable window functions on top of the result set?

As far as I understand a window function is applied after JOIN, WHERE, GROUP BY and HAVING (so those can be pushed down), but before ORDER BY and LIMIT.

**Comment by furkansahin** [comment]
> Quick question: Are we also planning to implement non-pushdownable window functions on top of the result set?

Yes, we do.

I still continue to research and in a couple of days, we will have a meeting with you and @onderkalaci  to discuss the implementation details.

**Comment by onderkalaci** [comment]
> As far as I understand a window function is applied after JOIN, WHERE, GROUP BY and HAVING (so those can be pushed down), but before ORDER BY and LIMIT (so those can no longer be pushed down in case of a non-pushdownable window function)

That seems accurate, posting the related Postgres [docs](https://www.postgresql.org/docs/10/static/queries-table-expressions.html#QUERIES-WINDOW) for reference.

**Comment by onderkalaci** [comment]
@furkansahin Shall we close this PR now since we're implementing it in # 2008?

**Pull request closed without merging**
