### PR TITLE
[WIP] Fix getting database name list at task tracker

### LINKED ISSUE #2525: Lingering "pg_merge_job_" schemas are not cleaned up
Task-tracker creates some intermediate tables during the execution (and generally! drops them at the end of the execution). On the workers, all the tables are created on schemas prefixed with `pg_merge_job_`. In some cases, task-tracker fails to clean-up those schemas/tables. So, they might stay forever there.

The code is written to clean-up them, but it turns out that it doesn't. There is probably a bug there.

Related code: 

Task-tracker bg worker at init:

https://github.com/citusdata/citus/blob/d63cbf382288358533b71d907f6a3a7fc8a1df5f/src/backend/distributed/worker/task_tracker.c#L210-L223

https://github.com/citusdata/citus/blob/d63cbf382288358533b71d907f6a3a7fc8a1df5f/src/backend/distributed/worker/task_tracker.c#L359-L419

Because of that, pg_upgrade may fail. 

```
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
```

The current work around is to manually call `SELECT worker_cleanup_job_schema_cache();
` on the workers.

### PR DESCRIPTION
**Pull request by onlined**
The list was fetched by a function called DatabaseNameList but it
became unusable with new Postgres versions, so it was set to NIL.
This change creates the function again, which scans `pg_database` for
getting database name list.

Fixes #2525.

DESCRIPTION: Fix getting database name list task tracker job schema cleanup

### CODE REVIEW

**Comment by onlined** [comment]
Not because of this change, but there is a flaw in current design: Task tracker worker connects all the databases except `template0` (it's not connectable) and runs cleanup UDF. On databases Citus installed this works as expected but on the other databases a warning is logged:
```
CONTEXT:  while executing command on localhost:9700
WARNING:  function worker_cleanup_job_schema_cache() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by marcocitus** [comment]
Woah, interesting. I think I never saw that comment.

#3850 removes task-tracker, but we'll initially still use job schemas for re-partitioning and we should actually clean those up even after #3850.

**Comment by onderkalaci** [comment]
> Should it be fixed in this PR? Or is it a future PR's concern?


I guess it should be fixed in this PR as this PR is introducing the error. Though, it doesn't seem we have an easy of getting the extensions created on each database.

As we call the relevant function only at startup of the bg worker (probably we should do similar on adaptive executor), it seems that we can implement something inefficient.

Is it possible to connect to each database, and execute a query like the below to find which databases has Citus extension created?
```SQL
SELECT                    
1
FROM 
pg_catalog.pg_extension e LEFT JOIN pg_catalog.pg_namespace n ON n.oid = e.extnamespace 
LEFT JOIN pg_catalog.pg_description c ON c.objoid = e.oid AND c.classoid = 'pg_catalog.pg_extension'::pg_catalog.regclass
WHERE e.extname = 'citus'
ORDER BY 1;
```

^ this is a variant of what `\dx`  does

**Comment by onlined** [comment]
Currently, at startup, `TrackerCleanupJobSchema` puts a `WorkerTask` for every database except `template0` in a task queue, then main loop calls `ManageWorkerTasksHash`. `WorkerTask` takes a query to be executed, in this case that query is `SELECT worker_cleanup_job_schema_cache();`. So with current design what you are saying (check extension and then execute UDF) is not possible. There are three ideas I thought of:

1. We can add a function pointer to `WorkerTask` and change processing function (`ManageWorkerTask`) to use function rather than query if function pointer is not `NULL`.
2. We can do what `ManageWorkerTask` do (opening new connections to local databases) in `TrackerCleanupJobSchema` and eagerly call UDF.
3. We can start a new background worker for each database and we can do the checking and calling there.

I feel like 3 is the best of these and 1 is the fastest to implement, but I'm not sure as I don't have any experience with the project. But I think 2 is not very good since it blocks task tracker initially.

**Comment by SaitTalhaNisanci** [comment]
We can possibly close this as we removed task tracker

**Comment by marcocitus** [comment]
We still have the same problem in the re-partitioning functions though.

**Comment by SaitTalhaNisanci** [comment]
I think we can close this PR because there are some edge cases that require complicated solutions for this cleanup logic. We removed task-tracker but even if it was here, we would create the task-tracker process and assign the cleanup task to it, then it would try to do the cleanup as a high priority task but there isn't any guarantee that there isn't a parallel repartition join query being run during that cleanup through adaptive-executor. If that is the case we are basically removing the schema that is in use.

There are some solutions to that but they are complicated mainly because there isn't a function that is run after _PG_init is run before accepting any queries. One option is using the maintenance daemon but then there is no guarantee when that gets started so there can still be in queries in parallel. And it can't be done in _PG_init because we can't read tables there.

Users can run `worker_cleanup_job_schema_cache` UDF to cleanup leftovers but this should also not be run in parallel with other repartition joins.

We will probably change the repartition join structure soon so implementing the complicated solutions don't really seem worthy at this point.

**Pull request closed without merging**
