### PR TITLE
Remove csql

### LINKED ISSUE #622: Deprecate csql
We added native COPY support for data ingestion, and this removes the motivation for having a separate ``\stage`` command. Once we deprecate ``\stage`` (tracked in #590), we should look to remove csql and all related Makefile and regression test dependencies.

### PR DESCRIPTION
**Pull request by lithp**
Fixes #622. Also removes the multi_fdw tests as they relied on \stage.

Relies on and is blocked by #630

### CODE REVIEW

**Comment by marcocitus** [comment]
There are a couple of functions that may be worth removing, since only stage relies on them:
- master_get_local_first_candidate_nodes
- master_get_round_robin_candidate_nodes
- master_stage_shard_row
- master_stage_shard_placement_row

@samay-sharma @saicitus Are these functions used in any custom scripts as far as you're aware?

**Comment by lithp** [comment]
I was planning on removing those in a second PR, it came as a separate
ticket and this is already a lot of files to look through.

**Comment by marcocitus** [comment]
ok, makes sense. I guess this ends up being a pretty straight-forward change. I like the shorter compile time, 53k lines of code left, down from 83k.

**Comment by anarazel** [comment]
On 2016-08-12 05:44:52 -0700, Marco Slot wrote:
> There are a couple of functions that may be worth removing, since only stage relies on them:
> - master_get_local_first_candidate_nodes
> - master_get_round_robin_candidate_nodes
> - master_stage_shard_row
> - master_stage_shard_placement_row
> 
> @samay-sharma @saicitus Are these functions used in any custom scripts as far as you're aware?

Hm, the first two seem quite useful to have.   I also wonder whether we
want the latter two as the basis for functionality in mx, to avoid
requiring superuser.

**Comment by sumedhpathak** [comment]
@lithp could you check why regression tests are failing? Assigned PR to @aamederen

**Comment by lithp** [comment]
@jasonmp85 I'm sorry I keep pinging you :disappointed: This one I'm pretty sure is your domain. The [travis build script](https://github.com/citusdata/tools/blob/develop/travis/pg_travis_multi_test#L6) hardcodes check-multi-fdw as a target, but this PR removes that series of tests and fails. What's the best way forward? Should I keep the check-multi-fdw target but have it no-op?

**Comment by jasonmp85** [comment]
> What's the best way forward?

Let's release a new version of the Travis build scripts?

**Comment by lithp** [comment]
@aamederen Travis is happy, read for you :)

**Comment by jasonmp85** [comment]
I merged #630 today so took the liberty of rebasing and fixing conflicts for this review (hopefully that's not too forward).

Anyhow, tests should be passing and the branch should now be up-to-date so we can kill this off as soon as the reviewer says :shipit:!

**Comment by jasonmp85** [comment]
Oops. Got scared when I saw the affected file count go down, then realized the original pull request included commits that are now in master. Makes sense.

**Comment by jasonmp85** [comment]
@lithp, I think the FDW tests you removed are still referenced in several `.gitignore` files. Can you clean those up?

**Comment by lithp** [comment]
Not too forward at all, thanks! Just removed the tests from `.gitignore`, nice catch.

**Comment by jasonmp85** [comment]
Oh, I suppose I'll have to update the build scripts once this is out or the nightly packages will fail when they try to use `update-alternatives` on `csql` or whatever. Hooray!

**Comment by lithp** [comment]
@aamederen friendly ping :)

**Comment by aamederen** [comment]
I don't much to add to @marcocitus and @jasonmp85's comments. After the commits are split, it looks like a :shipit: to me.

**Pull request merged**
