### PR TITLE
[Evaluate] Fix segfault in some CTE queries

### LINKED ISSUE #1038: SIGABRT in RouterSelectTask
To reproduce (on master with pg 9.6):

```
CREATE TABLE test (x int, y int, z int);
SELECT master_create_distributed_table('test', 'x', 'hash');
SELECT master_create_worker_shards('test', 16);
WITH result AS (
 UPDATE test SET y = z WHERE x = 10 AND z in (1, 2, 3, 4) RETURNING *
)
SELECT * FROM result ORDER BY z;
```

Backtrace:
```
#2  0x00000000008197cb in ExceptionalCondition (conditionName=conditionName@entry=0x7f03eeaee928 "!(rte->rtekind == RTE_RELATION)", 
    errorType=errorType@entry=0x7f03eeae6fba "FailedAssertion", fileName=fileName@entry=0x7f03eeaf3b42 "utils/ruleutils_96.c", lineNumber=lineNumber@entry=3155)
    at assert.c:54
#3  0x00007f03eeade23c in get_update_query_def (query=query@entry=0x17f6bc0, context=context@entry=0x7fff5d955960) at utils/ruleutils_96.c:3155
#4  0x00007f03eead8c0a in get_query_def_extended (query=0x17f6bc0, buf=buf@entry=0x18503e8, parentnamespace=0x1852ff8, distrelid=distrelid@entry=0, 
    shardid=shardid@entry=0, resultDesc=resultDesc@entry=0x0, prettyFlags=0, wrapColumn=0, startIndent=0) at utils/ruleutils_96.c:1915
#5  0x00007f03eead8cd4 in get_query_def (query=<optimized out>, buf=buf@entry=0x18503e8, parentnamespace=<optimized out>, resultDesc=resultDesc@entry=0x0, 
    prettyFlags=<optimized out>, wrapColumn=<optimized out>, startIndent=0) at utils/ruleutils_96.c:1844
#6  0x00007f03eead8e71 in get_with_clause (query=query@entry=0x182a358, context=context@entry=0x7fff5d955b50) at utils/ruleutils_96.c:2037
#7  0x00007f03eeaddf2b in get_select_query_def (query=query@entry=0x182a358, context=context@entry=0x7fff5d955b50, resultDesc=resultDesc@entry=0x0)
    at utils/ruleutils_96.c:2070
#8  0x00007f03eead8bf6 in get_query_def_extended (query=query@entry=0x182a358, buf=buf@entry=0x18503e8, parentnamespace=parentnamespace@entry=0x0, 
    distrelid=distrelid@entry=0, shardid=shardid@entry=0, resultDesc=resultDesc@entry=0x0, prettyFlags=0, wrapColumn=0, startIndent=0) at utils/ruleutils_96.c:1911
#9  0x00007f03eead8cd4 in get_query_def (query=query@entry=0x182a358, buf=buf@entry=0x18503e8, parentnamespace=parentnamespace@entry=0x0, resultDesc=resultDesc@entry=0x0, 
    prettyFlags=prettyFlags@entry=0, wrapColumn=wrapColumn@entry=0, startIndent=0) at utils/ruleutils_96.c:1844
#10 0x00007f03eead8cff in pg_get_query_def (query=query@entry=0x182a358, buffer=buffer@entry=0x18503e8) at utils/ruleutils_96.c:441
#11 0x00007f03eeac4c60 in RouterSelectTask (originalQuery=originalQuery@entry=0x182a358, restrictionContext=0x1846260, placementList=placementList@entry=0x7fff5d955cf0)
    at planner/multi_router_planner.c:1850
#12 0x00007f03eeac60ea in CreateSingleTaskRouterPlan (originalQuery=originalQuery@entry=0x182a358, query=query@entry=0x17f6cd8, 
    restrictionContext=restrictionContext@entry=0x1846260) at planner/multi_router_planner.c:209
```

When it fails the assertion that it's passed a RTE_RELATION it actually receives an RTE_FUNCTION.

### PR DESCRIPTION
**Pull request by byucesoy**
This is not a exact proper fix for the issue #1038. Intention of this PR is to show what is in my mind. For actual PR we need to check for corner cases, other possible usages etc.

### CODE REVIEW

**Comment by byucesoy** [comment]
Hi @anarazel could you have a look for this PR? I am not exactly sure if what I did is the correct way to fix the issue.

Summary: A query crashes becuse we encode the relation as RTE_FUNCTION (to be able to store extra data for CITUS_RTE_SHARD) but while deparsing the query we have an assert which requires rte->rtekind == RTE_RELATION. I did two things to fix it.

1-)Change assert to accept if GetRangeTblKind(rte) == CITUS_RTE_SHARD also.

2-)After doing this, Citus did not crash but cannot generate correct deparsed query to send the workers. Problem is, in that code path, we qualify column names in the query by prepending table name to them but we do not add shard_ids to that table names(We do add shard id to actual table name). Generating column name logic is in the get_variable function which seems to affect lots of places and it is difficult to change it without breaking other places. So I did something else, I added an alias for table name, which is just table name without the shard id, which makes wrongly qualified column names valid. However this feels little hacky and I wanted to take your opinion about it.

**Comment by mtuncer** [comment]
this has a lot of code repetitions spread to many places. May get us in trouble in the future.

**Comment by jasonmp85** [comment]
> This has a lot of code repetitions spread to many places.

I'm also pretty uncomfortable with this solution (even though it's possibly only a prototype?)

I gave this a brief look and haven't yet found anything more straightforward. The crux of this problem is "support modifying CTEs in queries which can be router-planned to hit a single shard", right?

A first stab at fixing the `Assert` crash would be to reject such queries with an error (better than the status quo), then fix subsequently with something (still trying to figure out what "something" is).

**Comment by metdos** [comment]
@byucesoy, as we talked, when you have time, could you add a note about which use cases we will not support if we simply error out?

**Comment by anarazel** [comment]
I think it's, for now, completely reasonable to forbid modifying tables from within CTEs.

**Pull request closed without merging**
