### PR TITLE
Fix problems with make check

### PR DESCRIPTION
**Pull request by JelteF**
This fixes two problems:
1. Allow `make check -j20` to work, by disabling parallelism. This was
   reported by a user in #7432
2. Actually run all the tests by forwarding to `make check` instead of
   `check-full`, because confusingly `check-full` does not run all the
   tests.

### CODE REVIEW

**Review by thanodnl — APPROVED** [review]
Great, makes the devcontainer even easier to use!

**Comment by crabhi** [comment]
Hi, I'm not sure this actually fixes the issues. I experienced the problem running `make` in the folder `src/test/regress`. There are two issues:

There's an environment variable `$MAKEFLAGS` set to `-j 8` in the container and the tests can't run in parallel because they try to overwrite something in the `tmp_check` or `tmp_citus_test` directory.

Running the tests with `make -j 1` works. Otherwise, it doesn't run even the `check-full` suite. It runs only `check-multi` and then `make` doesn't run anything else because in the meantime `check-multi-mx` errored out.

**Comment by thanodnl** [comment]
> Hi, I'm not sure this actually fixes the issues. I experienced the problem running `make` in the folder `src/test/regress`. 

I have verified the `-j` behaviour with this patch. It actually runs the tests sequentially when run now from the devcontainer.

It is unclear if all tests work locally from the devcontainer at the moment because I did hit an assert during the run, which I am still investigating, but is orthogonal to the initial issue of all tests running in parallel.

Due to the assert the tests stopped midway through, so there might be certain suites that don't work directly in the devcontainer due to their reliance on certain python tools which as installed in a pipenv inside the container, not in the system. eg. the failure tests we generally run from the test subdirectory while invoking them in a pipenv like

```bash
cd src/test/regress
pipenv run make check-failure
```

Nevertheless, this PR fixes the initial observation of running all tests in parallel causing races on `src/test/regress/check_tmp/`.

**Comment by crabhi** [comment]
@thanodnl Thanks for looking into this.

> we generally run from the test subdirectory while invoking them in a pipenv

That's what I was trying to say. I was running the tests only from the subdirectory and with pipenv, because that's what's been documented in [CONTRIBUTING.md](https://github.com/citusdata/citus/blob/main/CONTRIBUTING.md#debian-based-linux-ubuntu-debian).

I wasn't able to run all the suites successfully but that's probably a completely separate issue from this PR.

I think this PR is **correct**. It just doesn't address my observation because I was in a subdirectory so I probably wasn't influenced by the top-level Makefile. Anyway, let's not spend more time here. 😃

**Pull request merged**
