### PR TITLE
Replace \stage With \copy in Regression Tests

### LINKED ISSUE #547: Replace \stage with COPY in regression tests
Two notes;

- COPY uses the size of transmitted data to calculate the shard size. Therefore, this change will change min/max values of current shards. Playing with the shard max size in regression tests would help to keep shard counts same.

- Currently, COPY creates new shards randomly, after #489 is merged, it will be round-robin as it is in regression tests now.

### PR DESCRIPTION
**Pull request by aamederen**
Fixes #547

This change removes all references to \stage in the regression tests
and puts \COPY instead. Doing so changed shard counts, min/max
values on some test tables (lineitem, orders, etc.).

# Review Tasks

  - [x] Lowercase `\copy` to match PostgreSQL's style for local/psql-level functions (as opposed to (Postgre)SQL keywords)
  - [x] Remove references to _stage_ in the comments in `multi_schedule` and `multi_task_tracker_extra_schedule`
  - Remove _stage_ references in other files
    - [x] `multi_hash_pruning`
    - [x] `multi_join_order_tpch_large`
    - [x] `multi_shard_modify`
    - [x] `multi_agg_distinct`
    - [x] `multi_agg_type_conversion`
    - [x] `multi_append_table_to_shard`
    - [x] `multi_large_shardid`
    - [x] `multi_master_delete_protocol`
    - [x] `multi_subquery`
  - Remove _stage_ from filenames
    - [x] `multi_stage_data`
    - [x] `multi_stage_large_records`
    - [x] `multi_stage_more_data`

### CODE REVIEW

**Comment by jasonmp85** [comment]
So I just looked over this and it mostly looks good. I was concerned about the changing min/max values, and talked with @marcocitus a bit about whether there is a risk new PostgreSQL versions could change them all again (there is, but small). Thought a bit that we could mess around with shard size to try to get a smaller diff, but ultimately I think it's best that our tests reflect our default behavior where they can, so we will take the hit and make this large change rather than try to preserve the existing output by meddling with some setting.

Additionally, I noticed there were some conflicts, so I took the liberty of rebasing your changes, fixing the conflicts, and fixing any now-broken tests. Assuming you don't have any local changes, it should be possible to update your local branch with the rewritten commit using:

  * `git fetch`
  * `git checkout replace_stage_with_copy_in_tests`
  * `git reset --hard replace_stage_with_copy_in_tests`

Finally, while this code review doesn't address _all_ uses of `\stage` (i.e. the `fdw` tests have some), it is intended to move us towards removing `\stage` (and `csql`) altogether. Because of that I'd like it if we could scrub all mentions of _stage_ from the files here and replace it with _copy_ instead (even in comments, file names, etc.). That's basically most of my feedback, which I've collected in a checklist up top.

After the checklist items have been addressed, :shipit: (no need to wait for another round of review, since my requests are mostly `s/stage/copy/g`). 👍

**Comment by jasonmp85** [comment]
Oh, the other bit of feedback is that I really don't like `\COPY`, since it looks just like `COPY`, which is server-side. For the same reason I never liked `\STAGE`, though in that case it was a little more complicated.

So if we mean client-side, use `\copy`. Reserve uppercase for the server-side variant (PostgreSQL's own docs do the same).

**Comment by aamederen** [comment]
Hey @jasonmp85, about removing all "stage" mentions from the files, we had a discussion with @ozgune at #562. Could you talk about this with Ozgun and maybe we can find an alternative name for the act of loading data.

**Comment by lithp** [comment]
This doesn't remove the references to \stage from `multi_fdw_stage_data`

**Comment by lithp** [comment]
Oh, nevermind. Git strikes again :(

**Comment by lithp** [comment]
This still uses stage: https://github.com/citusdata/citus/blob/2f594f087dfdfb376235d07e64b8ecb838525feb/src/test/regress/input/multi_fdw_stage_data.source

**Comment by aamederen** [comment]
@lithp we will continue using \stage with file_fdw for now because we got an error like this:
```
ERROR:  cannot copy to foreign table "lineitem_330001"
DETAIL:  (null)
```
I couldn't remember the discussion we had about this but I remember that we decided to let them be for now.

**Comment by jasonmp85** [comment]
> I couldn't remember the discussion we had about this but I remember that we decided to let them be for now.

Yup, which is why I didn't bring them up in the PR.

**Comment by jasonmp85** [comment]
A large problem with the word _stage_ is that it implies the data is not fully loaded, especially for those coming from an ETL background. `load` is also very clear to me, though this kind of feels like a product decision. I'll run it by @ozgune today and we'll pick one or the other and get this merged.

**Comment by lithp** [comment]
@jasonmp85 Friendly ping on this, have you had a chance to talk to Ozgun?

**Comment by marcocitus** [comment]
To speed up this pull request and unblock #737, could we skip the renaming discussion for now? 

We should probably use more universally-accepted language, but stage has become Citus Data jargon for loading data into an append-distributed table. In master_stage_protocol.c have comments like "Routines for staging PostgreSQL table data as shards into the distributed cluster.". This file contains implementations of master_create_empty_shard and master_append_table_to_shard, which have absolutely no relation to \STAGE. The word stage is simply used as jargon.

If there are no objections, then we'll proceed with #737 tomorrow.

**Comment by jasonmp85** [comment]
Sorry, a little delayed what with all the packaging interrupts (as ever).

In standup right now; going to chime in with this.

**Comment by jasonmp85** [comment]
After discussing this with @ozgune and @begriffs, Ozgun said the major consideration was just that we have consistency and he didn't care one way or the other. With that in mind, I asked Joe to get me a list of places we use _stage_ or _staging_ in the docs. Here's what he found:

## `admin_guide`/`upgrading_citus`
  * _If you are upgrading the master, then you should stop all data-loading/appending and **staging** before copying out the metadata._
  * _This will come into play when **staging** data, not when querying data._

## `dist_tables`/`append_distribution`
  * _you can append the contents of the staging table to the specified shard_

## `performance`/`scaling_data_ingestion`
(Many references to a staging table)

## `reference`/`configuration`
  * _When the source file's size (which is used for staging) for one shard exceeds this configuration value_

**Comment by jasonmp85** [comment]
So from the documentation, most uses of "stage" are in reference to a staging table (i.e. a non-important table created for the purpose of loading some part of the data before e.g. appending to a shard). Because of this, we'll reserve "staging" to mean the above, and use "loading" or "data loading" for the idea of putting data into a cluster.

**Pull request merged**
