### PR TITLE
Cause an Assertion Failure

### PR DESCRIPTION
**Pull request by fdr**
commit 74a3be36073cc66bc025ad71468bb39e8ed0205e
Author: Daniel Farina <daniel@citusdata.com>
Date:   Wed Aug 3 16:12:16 2016 -0700

    Make an assertion failure
    
    If one compiles with `--enable-cassert --enable-debug`, and causes an
    `ereport` in `master_create_worker_shards`, an assertion failure
    follows.

commit 725736088097ca3b4f987bb182c9a70e81ff207f
Author: Daniel Farina <daniel@citusdata.com>
Date:   Wed Aug 3 14:36:31 2016 -0700

    Eliminate some non-failing tests
    
    To bring better focus on the diff of the bug report that is to follow,
    adjust the test schedule and break it out into this diff.

### CODE REVIEW

**Comment by jasonmp85** [comment]
A description of the expected and actual behavior would be good?

**Comment by fdr** [comment]
Expected behavior: do not crash with an assertion failure.
Actual behavior: crashes the server with an assertion failure.

**Comment by anarazel** [comment]
And it doesn't currently crash with an assertion failure... Perhaps post the actual assertion failure you're seeing, and possibly a backtrace?

**Comment by fdr** [comment]
Here's a script that reproduces it.

```sh
#!/bin/sh
set -uex
# Set POSTGRES_DIR and CITUS_DIR environment variables.

pushd $POSTGRES_DIR
git checkout REL9_5_3
./configure --prefix=/tmp/pg --enable-cassert --enable-debug
make -sj6 install
popd


pushd $CITUS_DIR
PATH=/tmp/pg/bin:$PATH ./configure
make install && make -C src/test/regress check-multi || true # because it fails
cat ./src/test/regress/tmp_check/master/log/postmaster.log
# [...]
# ERROR:  replication_factor must be positive
# STATEMENT:  SELECT master_create_worker_shards('test_schema_support.nation_hash', 4, -1);
# ERROR:  could not find any shards
# DETAIL:  No shards exist for distributed table "nation_hash".
# HINT:  Run master_create_worker_shards to create shards and try again.
# STATEMENT:  INSERT INTO test_schema_support.nation_hash(n_nationkey, n_name, n_regionkey) VALUES (6, 'FRANCE', 3);
# TRAP: BadArgument("!(shardId != 0)", File: "utils/resource_lock.c", Line: 75)
# LOG:  server process (PID 32504) was terminated by signal 6: Aborted
# DETAIL:  Failed process was running: SELECT * FROM test_schema_support.nation_hash WHERE n_nationkey = 6;
# LOG:  terminating any other active server processes
# WARNING:  terminating connection because of crash of another server process
# DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
# HINT:  In a moment you should be able to reconnect to the database and repeat your command
# [...]
popd
```

**Comment by jasonmp85** [comment]
Addressed by #706.

**Pull request closed without merging**
