### PR TITLE
Add more tests for single node citus - distributetd tables

### PR DESCRIPTION
**Pull request by onderkalaci**
Single-node Citus "just worked" when we enabled shards on the coordinator.  We have added few tests and fix few bugs on that scenario in the past.

With this commit, we are expanding the test coverage of the single-node citus experience. The idea is that any user should be able to Citus on a single node. So, we should make sure that all features works fine.

We still need some more tests for reference tables and enterprise specific queries. I'll add them with separate PRs.

The slight downside of the PR is that the execution time of the test increase from `~1.5 seconds` to `~4 seconds` on my laptop, but I guess we can live with that.

### CODE REVIEW

**Comment by SaitTalhaNisanci** [comment]
I have one general question/suggestion here. In a high level, we have some tests that we expect to work with `citus`, no matter if it is a single node or not. So currently we are writing the same tests that we already have for non-single mode and we basically have `minimum` tests in the single node case. We already saw this with re-partition joins, task-tracker etc( as in they were problematic).

So as we already have tests and we can reuse the same tests, can't we execute some of the other tests files with a single node? Going a bit further we could have `single_node_schedule` where we add tests files that we want to have. For example lets say we already have x,y,z test files in multi_schedule. We can basically reuse them in `single_node_schedule` (we can add an alternative output if necessary). Some of the advantages this would have:

- When adding a new test to a file, if it is already in `single_node_schedule` we will see how it works in single node as well.
- We will have much better test coverage for single node citus.

We can run the single node tests in a separate parallel job on circleci so the overall test time wont be slower.

**Comment by onderkalaci** [comment]
> In a high level, we have some tests that we expect to work with citus, no matter if it is a single node or not

agreed, but which of those? Finding that doesn't seem easy.

> (we can add an alternative output if necessary)

Maintaining those are really painful, and I can see quite a lot of the test outputs needs to be changed.

> We will have much better test coverage for single node citus.

That's true, on the other hand it is not very much necessary to test all different things on single node. For example, we have hundred (or thousands?) of CTE tests which are important to see the behaviour of the planned, and which doesn't add value to re-run on single node. What we want to see is that there is no weird things happening when a CTE is executed in a few different cases.

In the past, I added `mx_tpch_*` queries to the schedule with a similar intent (and many other MX tests as well). At that time, Marco noted me that these don't have much value. Looking back, he was right, many  of the MX tests don't fail alone ever --  not adding much value to our tests --, and it is always extra work to keep those test outputs when anything changes.

Still, if you are up for finding those tests, and adding them to a new schedule, I'd be OK with that.

**Review by marcocitus — APPROVED** [review]

**Comment by marcocitus** [comment]
Are there any major gaps not covered after this PR?

**Comment by onderkalaci** [comment]
> Are there any major gaps not covered after this PR?

Maybe a little more complex transaction tests on distributed tables and few more generic reference table tests. Plus, working on an enterprise test patch now

**Comment by onderkalaci** [comment]
> Maybe a little more complex transaction tests on distributed tables and few more generic reference table tests. Plus, working on an enterprise test patch now

I'll open PRs for the remaining parts btw

**Pull request merged**
