### PR TITLE
When a domain or type is used in a distribution column, the drop type/domain operation is not allowed

### PR DESCRIPTION
**Pull request by TsinghuaLucky912**
hello：

# The environment
Ubuntu 22.04 LTS + PostgreSQL15.0 + main

set citus.shard_count = 2;
set citus.override_table_visibility to off;
set citus.log_remote_commands = on;

# The problem
## one
create domain posint as integer check (value > 0);
-- SELECT run_command_on_workers('create domain posint as integer check (value > 0)');
create table t1(id posint);
select create_distributed_table('t1', 'id');
drop domain if exists posint cascade;

## second
create type mytype as (id int,name varchar(16));
create table t2(value mytype);
select create_distributed_table('t2', 'value');
drop type mytype cascade;

-- here
drop table t1; // error cache
drop table t2;

# The note
I obtained DropStmt from Utility hook for judgment, mainly using pg_type and pg_dist_partition system table contents. If you have any better ideas, I'm happy to share them with you. Thank you

### CODE REVIEW

**Comment by onurctirtir** [comment]
@naisila, this looks very similar to #6393 ?

**Comment by TsinghuaLucky912** [comment]
> @naisila, this looks very similar to #6393 ?

Thanks, it feels like yes I'm going to close my merge as there are still some issues, I'll take a look at https://github.com/citusdata/citus/pull/6393/files

**Comment by naisila** [comment]
@TsinghuaLucky912 @onurctirtir Note that my PR is only for types, not domains.

**Comment by TsinghuaLucky912** [comment]
@naisila @onurctirtir 

I saw your code and I think your idea is far better than mine. I copied your code back to the latest main and found that it works very well:

`
postgres=# drop domain if exists posint cascade;
ERROR:  Can't drop type "public.posint" because it is used in the partition column "id" of Citus table "t1"
postgres=# 
postgres=# drop type mytype cascade;
ERROR:  Can't drop type "public.mytype" because it is used in the partition column "value" of Citus table "t2"
postgres=#
`

Attached is patch, I hope it is useful to you.
[domain.txt](https://github.com/citusdata/citus/files/10080566/domain.txt)

**Pull request closed without merging**
