### PR TITLE
Bump Citus to 7.5devel

### PR DESCRIPTION
**Pull request by velioglu**

### CODE REVIEW

**Comment by lithp** [comment]
@mtuncer I mean, kind of. We could require that you copy it yourself before running the build, and tell appveyor to do so.

**Comment by mtuncer** [comment]
Is it possible to make it post-build action such that it would be created when the build succeeds ?

It was needed when installing citus from contrib folder.

**Comment by lithp** [comment]
It's not ideal but I've opened https://github.com/citusdata/citus/pull/2173 to help us remember to update `citus.control`.

Unfortunately we don't have much control over the build process, we rely on `Mkvcbuild.pm`. I suppose we could add another patch which changes `Mkvcbuild.pm` and does the copy for us?

**Comment by jasonmp85** [comment]
FWIW `Makefile`s _must_ use tabs, not spaces. If this PR was generated by a tool, the tool needs to be fixed to use tabs.

**Comment by jasonmp85** [comment]
Aaaaand the `citus_version.h` file is also out of date…

**Pull request merged**
