### PR TITLE
Open transaction block when isolation level uses snapshot

### PR DESCRIPTION
**Pull request by derokhin-datagile**
It is offered to always open transaction block when isolation level is repeatable-read or serializable. This will help to solve issue https://github.com/citusdata/citus/issues/7366 when at least "repeatable-read" isolation level is default.

### CODE REVIEW

**Comment by derokhin-datagile** [comment]
> Could you give an example of a case that works with this change, but doesn't work without? I don't understand what difference happens for single statement transactions with repeatable read.

So there is issue https://github.com/citusdata/citus/issues/7366 . Short description of issue: there is a distributed table with shards on a single machine. We can get not consistent reading when we update and read that table asynchronously.

It happens because single "select sum( ..." statement actually transforms into two "select" statement on each shard and actual order of statements node is processing can be like this:
- first "select sum" on first shard
- commit transaction with updates
- second "select sum" on second shard.

Solution of this PR is open transaction block for single select statements when isolation level greater or equal of repeatable read. It will produce consistent read from one node when select statement will transform to two or more statements.

**Comment by JelteF** [comment]
Okay, the "single machine" seems the crux here. I agree that this change would solve it when all shards are present on a single node. I don't think that's a very common use case though. You'd still get inconsistent results when the data is spread around different nodes though. 

Do you have all shards on a single node?

**Comment by derokhin-datagile** [comment]
> Okay, the "single machine" seems the crux here. I agree that this change would solve it when all shards are present on a single node. I don't think that's a very common use case though. You'd still get inconsistent results when the data is spread around different nodes though.
> 
> Do you have all shards on a single node?

Of course it is not common use case when all shards on a single node.
There is recomendation about shard count: https://docs.citusdata.com/en/latest/faq/faq.html#how-do-i-choose-the-shard-count-when-i-hash-partition-my-data . So we can have many shards on one node. Solution of this PR will provide consistent reading from single select statement which will work only with shards of one node.

And yes, you're right: "You'd still get inconsistent results when the data is spread around different nodes though.". This is true when single select statement will work with many nodes.

**Comment by marcoslot** [comment]
I think this is only relevant in the case where someone does something like:
```sql
-- create a distributed table
CREATE TABLE counters (key int primary key, val int not null);
SELECT create_distributed_table('counters','key');

-- change the isolation level to serializable for this session only
SET default_transaction_isolation TO 'serializable';

-- do something that would be buggy in read committed / repeatable read
WITH current_val AS (SELECT key, val FROM counters WHERE key = 55)
UPDATE counters SET val = current_val.val +1 FROM current_val WHERE counters.key = current_val.key;
```
If the `default_transaction_isolation` level is `read committed`, then this would give unexpected behaviour because we would not propagate `BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE` like we would if we were in a transaction block.

Of course, it seems preferable as a user to change the `default_transaction_isolation` on all the nodes if serializable isolation at the node level is desirable. 

This change does nothing for cross-node snapshot isolation, which is primarily about having all transactions on worker nodes agree on which distributed transactions are committed.

This PR is probably still a minor improvement, though it also raises the question what the behaviour should be when the worker nodes are configured with `serializable` and the session is using `read committed`, but that's probably quite hypothetical.

**Comment by derokhin-datagile** [comment]
> I think this is only relevant in the case where someone does something like:
> 
> ```sql
> -- create a distributed table
> CREATE TABLE counters (key int primary key, val int not null);
> SELECT create_distributed_table('counters','key');
> 
> -- change the isolation level to serializable for this session only
> SET default_transaction_isolation TO 'serializable';
> 
> -- do something that would be buggy in read committed / repeatable read, without using a transaction block
> WITH current_val AS (SELECT key, val FROM counters WHERE key = 55)
> UPDATE counters SET val = current_val.val +1 FROM current_val WHERE counters.key = current_val.key;
> ```
> 
There is example from https://github.com/citusdata/citus/issues/7366 . One person makes update, second person reads data asynchronously. With applying this solution second person can make "SET default_transaction_isolation TO 'read repeatable';" for its session (or set it by default) and single select statements which will work with shards of one node will be consistent.
> 
> Of course, it seems preferable as a user to change the `default_transaction_isolation` on all the nodes if serializable isolation at the node level is desirable.
> 
Repeatable read level is also suitable for reading.

> This change does nothing for cross-node snapshot isolation, which is primarily about having all transactions on worker nodes agree on which distributed transactions are committed.

As discussed above, there is a recomendation https://docs.citusdata.com/en/latest/faq/faq.html#how-do-i-choose-the-shard-count-when-i-hash-partition-my-data and we can have many shards on one node. We can have consistent reading from single select statement which will work with shards from one node by applying this solution.

**Comment by JelteF** [comment]
Actually for same-node snapshot isolation it doesn't even have consistent impact, because Citus may decide to open multiple connections to the same node for parallelism reasons. And the snapshots of the different connections will be different.

**Comment by JelteF** [comment]
@marcoslot 

Afaict your example would already be fine, given the test below the one that this PR changes. There we already forward default_transaction_isolation when using CTEs.

**Comment by JelteF** [comment]
> Do you want to say even transaction block is started explicity with snapshot isolation it is possible to get not consistent data when request is working with single node?

Afaik yes. The unit at which Citus currently provides snapshot isolation is at the shard level, not the node level.

**Comment by marcoslot** [comment]
> With applying this solution second person can make "SET default_transaction_isolation TO 'repeatable read';" for its session (or set it by default) and single select statements which will work with shards of one node will be consistent.

There isn't much difference between repeatable read and read committed for single statement transactions, and the isolation level is already propagated for multi-statement transactions. Hence my assumption that this can only be relevant for setting the session to serializable, when the global config is at a lower isolation level, since serializable is meaningfully different.  (Though perhaps not demonstrated by my example)

Repeatable read is not more consistent than read committed, it mainly just determines how subsequent statements in the same transaction see the database. Repeatable read reuses first statement snapshot, while read committed gets a new snapshot per statement.

The isolation levels break down when multiple shard groups or nodes are involved, but apply quite cleanly when transactions always hit a single shard group.

**Pull request closed without merging**
