### PR TITLE
Fix self strncmp

### PR DESCRIPTION
**Pull request by jasonmp85**
DESCRIPTION: Fix bad foreign constraint name search

See the commit messages for more details.

### CODE REVIEW

**Comment by metdos** [comment]
This PR seems approved, any reason to keep this open?

**Comment by jasonmp85** [comment]
> This PR seems approved, any reason to keep this open?

Mostly my own paranoia that I changed behavior somewhere in all these variable renames… just wanted time to go over it thoroughly a second time. Doing so now and will merge.

**Comment by jasonmp85** [comment]
> Not sure whether this is worth adding a regression test. Fine with the PR as is.

I mostly considered the compiler warning its own kind of test to prevent the old behavior. I don't think this is necessarily worth another runtime test. I'll leave it as-is and merge.

**Comment by jasonmp85** [comment]
Double-checked everything; looks good. Merging.

**Pull request merged**
