### PR TITLE
Make citus_stat_statements_reset() super user function

### PR DESCRIPTION
**Pull request by mtuncer**
This PR revokes all rights on citus_stat_statements_reset() UDF from public.

### CODE REVIEW

**Comment by mtuncer** [comment]
does not need description as this is a continuation of landlord work

**Comment by marcocitus** [comment]
Should we do the same for `citus_stat_statements`?

**Comment by mtuncer** [comment]
Do you mean citus_stat_staments view or UDF ?

pg_stat_statements view is available for public. IF we are to limit citus_stat_staments view, we should also limit the UDF.

**Comment by marcocitus** [comment]
> I was thinking we can revoke rights from citus_stat_statements() and citus_query_stats() while granting it for the view. pg_stat_statements sort of handles its own security and after the join with citus_stat_statements() you can only see your own queries since pg_stat_statements hides the queryIds, but you can see all queries in citus_query_stats().

ok, nvm, seems you cannot grant select permission on the view without the ability to execute the function

**Comment by marcocitus** [comment]
I think making the function callable and the view readable only by `pg_read_all_settings` makes sense, though doing it in the extension script creates a hard dependency on `pg_stat_statements`, which is not something we want.

I guess the current PR might be an ok starting point and users will need to adapt to their needs, e.g. Cloud will want to grant execute on `citus_stat_statements_reset()` to `pg_read_all_stats`.

**Comment by mtuncer** [comment]
I am not for this 👎 
role `pg_read_all_stats` is available for PG10+, it is not available in PG9.6 which we still support.

**Comment by mtuncer** [comment]
also current patch to pg_stat_statements has following
```
+-- Don't want this to be available to non-superusers.
+REVOKE EXECUTE ON FUNCTION pg_stat_statements_reset() FROM pg_read_all_stats;
```

my take:
- leave citus_stat_statements view (and related functions) as callable from public
- make citus_state_statements_reset() super user function

**Pull request merged**
